"""Category catalog for LT - Generated from tree file."""

# Category ID to Name mapping
CATEGORY_NAME_MAP: dict[str, str] = {
    "249": "Dovanos užsienyje",
    "251": "Oro pramogos",
    "252": "Skrydis oro balionu",
    "253": "Šuolis parašiutu",
    "254": "Skrydis parasparniu",
    "255": "Apžvalginiai skrydžiai lėktuvu",
    "256": "Skrydis sklandytuvu",
    "257": "Vandens pramogos",
    "258": "Vandens parkai",
    "259": "Žvejyba",
    "260": "Plaukimas laivu ir jachta",
    "261": "Nardymas",
    "262": "Plaukimas baidare",
    "263": "Kaitavimas",
    "264": "Vandenlentės",
    "265": "Aktyvios pramogos",
    "266": "Šaudymas",
    "267": "Jodinėjimas",
    "268": "Auto / motopramogos",
    "269": "Kartingai",
    "270": "Pramogų parkai",
    "271": "Boulingas",
    "272": "Driftas",
    "273": "Grožis",
    "274": "Veido procedūros",
    "275": "Plaukų procedūros",
    "276": "Kūno procedūros",
    "277": "Grožio kompleksai",
    "278": "Manikiūras, pedikiūras",
    "279": "Procedūros vyrams",
    "280": "Poilsis Lietuvoje",
    "281": "Poilsis Druskininkuose",
    "282": "Poilsis Birštone",
    "283": "Poilsis Trakuose",
    "284": "Poilsis Palangoje",
    "285": "Poilsis Vilniuje",
    "286": "Poilsis Kaune",
    "287": "1 nakvynė",
    "288": "2 nakvynės",
    "289": "3 ir daugiau nakvynės",
    "290": "Poilsis dviem",
    "291": "Poilsis vienam",
    "292": "SPA ir masažai",
    "293": "SPA ir masažai dviem",
    "294": "Viso kūno masažai",
    "295": "Nugaros masažai",
    "296": "Masažų kompleksai",
    "297": "SPA procedūros",
    "298": "Masažai vyrams",
    "299": "Restoranai ir degustacijos",
    "300": "Vakarienės",
    "302": "Maisto degustacijos",
    "303": "Kulinarijos kursai",
    "304": "Kūrybiškos, linksmos",
    "305": "Fotosesijos",
    "306": "Žaidimai",
    "307": "Ekskursijos",
    "308": "Pamokos",
    "309": "Galvosūkių kambariai",
    "310": "Kinas",
    "311": "Sveikatinimas",
    "312": "Poilsis sanatorijoje",
    "313": "Sveikatinimo procedūros",
    "315": "Žiemos pramogos",
    "316": "Slidinėjimas",
    "375": "Dovanų rinkiniai",
    "376": "Parduotuvių dovanų čekiai",
    "377": "Prekybos centrų dovanų kortelės",
    "378": "Žurnalų ir leidinių prenumerata",
    "421": "Veido masažai",
    "429": "Golfas",
    "430": "Sportas, joga ir meditacija",
    "432": "Galvos masažai",
    "436": "Teatrai ir filharmonija",
    "439": "Superautomobiliai",
    "442": "Žurnalų prenumerata",
    "445": "Lamborghini",
    "446": "TESLA",
    "447": "Ferrari",
    "448": "Pusryčiai",
    "449": "Tamsa",
    "450": "Pasaulio virtuvės",
    "452": "Gerumo dovanos",
    "456": "Poilsis dvaruose ir pilyse",
    "460": "Spa ir masažai Vilniuje",
    "461": "Spa ir masažai Kaune",
    "465": "Poilsis Anykščiuose",
    "468": "Renginiai",
    "469": "Poilsis užsienyje",
    "473": "Poilsis Latvijoje",
    "476": "Pramogos Latvijoje",
    "477": "Poilsis Estijoje",
    "478": "Poilsis Lenkijoje",
    "479": "Miestų kortelės",
    "483": "Apsipirkimas internetu",
    "484": "Žurnalai",
    "485": "Maistas į namus",
    "486": "Nuotoliniai mokymai ir seminarai",
    "488": "Kitos šalys",
    "489": "Poilsis prie ežero",
    "490": "Poilsis prie jūros",
    "491": "Žygiai",
    "492": "Bagiai",
    "493": "Keturračiai",
    "494": "Motociklai",
    "495": "Dažasvydis",
    "496": "Virtuali realybė",
    "497": "SPA poilsis",
    "499": "Irklentės",
    "500": "Šratasvydis",
    "501": "Vandens batutai",
    "502": "Vandens motociklai",
    "503": "Dantų balinimas",
    "507": "Poilsis šeimai",
    "511": "Pilotavimo pamoka",
    "512": "Atpalaiduojamieji masažai",
    "513": "Limfodrenažiniai masažai",
    "514": "Tailandietiški masažai",
    "515": "Ajurvediniai masažai",
    "516": "Masažai nėščiosioms",
    "517": "Gydomieji masažai",
    "518": "Sportiniai automobiliai",
    "519": "Tankai",
    "520": "Monster truck",
    "521": "Džipai ir safaris",
    "522": "Dviračiai ir paspirtukai",
    "523": "Vairavimo pamokos",
    "524": "Baseinai ir pirtys",
    "525": "Valtys ir vandens dviračiai",
    "526": "Flyboard",
    "527": "Kitos vandens pramogos",
    "528": "Kovos menai",
    "529": "Laipiojimas",
    "530": "Menai ir mokymai",
    "531": "Kūrybinės pramogos",
    "532": "Kvepalų ir kosmetikos kūrimas",
    "533": "Šokių ir muzikos pamokos",
    "534": "Gėrimų degustacijos",
    "535": "Desertai",
    "536": "Restoranų čekiai",
    "537": "Knygos",
    "538": "Muziejai",
    "539": "Makiažas",
    "540": "Grožio mokymai",
    "546": "Plūduriavimas",
    "547": "Porsche",
    "549": "Darbostogos",
    "559": "Kabrioletai",
    "568": "Kavos degustacijos",
    "569": "Šampano degustacijos",
    "570": "Viskio degustacijos",
    "571": "Vyno degustacijos",
    "572": "Alaus degustacijos",
    "573": "Burnos higiena",
    "575": "Kraujo ir sveikatos tyrimai",
    "577": "Kitos paslaugos",
    "581": "Sveikatinimo programos",
    "613": "Jogos užsiėmimai ir pamokos",
}

# Category ID to URL mapping
CATEGORY_URL_MAP: dict[str, str] = {
    "249": "https://www.geradovana.lt/dovanos-uzsienyje",
    "251": "https://www.geradovana.lt/oro-pramogos",
    "252": "https://www.geradovana.lt/oro-pramogos/skrydis-oro-balionu",
    "253": "https://www.geradovana.lt/oro-pramogos/suolis-parasiutu",
    "254": "https://www.geradovana.lt/oro-pramogos/skrydis-parasparniu",
    "255": "https://www.geradovana.lt/oro-pramogos/apzvalginiai-skrydziai-lektuvu",
    "256": "https://www.geradovana.lt/oro-pramogos/skrydis-sklandytuvu",
    "257": "https://www.geradovana.lt/vandens-pramogos",
    "258": "https://www.geradovana.lt/vandens-pramogos/vandens-parkai",
    "259": "https://www.geradovana.lt/vandens-pramogos/zvejyba",
    "260": "https://www.geradovana.lt/vandens-pramogos/plaukimas-laivu-ir-jachta",
    "261": "https://www.geradovana.lt/vandens-pramogos/nardymas",
    "262": "https://www.geradovana.lt/vandens-pramogos/plaukimas-baidare",
    "263": "https://www.geradovana.lt/vandens-pramogos/kaitavimas",
    "264": "https://www.geradovana.lt/vandens-pramogos/vandenlentes",
    "265": "https://www.geradovana.lt/aktyvios-pramogos",
    "266": "https://www.geradovana.lt/aktyvios-pramogos/saudymas",
    "267": "https://www.geradovana.lt/aktyvios-pramogos/jodinejimas",
    "268": "https://www.geradovana.lt/auto-moto",
    "269": "https://www.geradovana.lt/auto-moto/kartingai",
    "270": "https://www.geradovana.lt/aktyvios-pramogos/nuotykiu-parkai",
    "271": "https://www.geradovana.lt/aktyvios-pramogos/boulingas",
    "272": "https://www.geradovana.lt/auto-moto/driftas",
    "273": "https://www.geradovana.lt/grozis",
    "274": "https://www.geradovana.lt/grozis/veido-proceduros",
    "275": "https://www.geradovana.lt/grozis/plauku-proceduros",
    "276": "https://www.geradovana.lt/grozis/kuno-proceduros",
    "277": "https://www.geradovana.lt/grozis/grozio-kompleksai",
    "278": "https://www.geradovana.lt/grozis/manikiuras-pedikiuras",
    "279": "https://www.geradovana.lt/grozis/proceduros-vyrams",
    "280": "https://www.geradovana.lt/poilsis-su-nakvyne",
    "281": "https://www.geradovana.lt/poilsis-su-nakvyne/poilsis-druskininkuose",
    "282": "https://www.geradovana.lt/poilsis-su-nakvyne/poilsis-birstone",
    "283": "https://www.geradovana.lt/poilsis-su-nakvyne/poilsis-trakuose",
    "284": "https://www.geradovana.lt/poilsis-su-nakvyne/poilsis-palangoje",
    "285": "https://www.geradovana.lt/poilsis-su-nakvyne/poilsis-vilniuje",
    "286": "https://www.geradovana.lt/poilsis-su-nakvyne/poilsis-kaune",
    "287": "https://www.geradovana.lt/poilsis-su-nakvyne/1-nakvyne",
    "288": "https://www.geradovana.lt/poilsis-su-nakvyne/2-nakvynes",
    "289": "https://www.geradovana.lt/poilsis-su-nakvyne/3-ir-daugiau-nakvynes",
    "290": "https://www.geradovana.lt/poilsis-su-nakvyne/2-asmenims",
    "291": "https://www.geradovana.lt/poilsis-su-nakvyne/1-asmeniui",
    "292": "https://www.geradovana.lt/spa-ir-masazai",
    "293": "https://www.geradovana.lt/spa-ir-masazai/spa-ir-masazai-dviem",
    "294": "https://www.geradovana.lt/spa-ir-masazai/viso-kuno-masazai",
    "295": "https://www.geradovana.lt/spa-ir-masazai/nugaros-masazai",
    "296": "https://www.geradovana.lt/spa-ir-masazai/masazu-kompleksai",
    "297": "https://www.geradovana.lt/spa-ir-masazai/spa-proceduros",
    "298": "https://www.geradovana.lt/spa-ir-masazai/masazai-vyrams",
    "299": "https://www.geradovana.lt/geras-skonis",
    "300": "https://www.geradovana.lt/geras-skonis/vakarienes",
    "302": "https://www.geradovana.lt/geras-skonis/degustacijos",
    "303": "https://www.geradovana.lt/geras-skonis/kursai",
    "304": "https://www.geradovana.lt/kurybiskos-linksmos-dovanos",
    "305": "https://www.geradovana.lt/kurybiskos-linksmos-dovanos/fotosesijos",
    "306": "https://www.geradovana.lt/aktyvios-pramogos/zaidimai",
    "307": "https://www.geradovana.lt/kurybiskos-linksmos-dovanos/ekskursijos",
    "308": "https://www.geradovana.lt/kurybiskos-linksmos-dovanos/pamokos",
    "309": "https://www.geradovana.lt/aktyvios-pramogos/galvosukiu-kambariai",
    "310": "https://www.geradovana.lt/kurybiskos-linksmos-dovanos/kinas",
    "311": "https://www.geradovana.lt/sveikatinimas",
    "312": "https://www.geradovana.lt/poilsis-su-nakvyne/poilsis-sanatorijoje",
    "313": "https://www.geradovana.lt/sveikatinimas/sveikatinimo-proceduros",
    "315": "https://www.geradovana.lt/ziemos-pramogos",
    "316": "https://www.geradovana.lt/ziemos-pramogos/slidinejimas",
    "375": "https://www.geradovana.lt/dovanu-rinkiniai",
    "376": "https://www.geradovana.lt/parduotuviu-dovanu-cekiai",
    "377": "https://www.geradovana.lt/pc-cekiai",
    "378": "https://www.geradovana.lt/leidiniu-prenumeratos",
    "421": "https://www.geradovana.lt/spa-ir-masazai/veido-masazai",
    "429": "https://www.geradovana.lt/aktyvios-pramogos/golfas",
    "430": "https://www.geradovana.lt/sveikatinimas/sporto-uzsiemimai",
    "432": "https://www.geradovana.lt/spa-ir-masazai/galvos-masazai",
    "436": "https://www.geradovana.lt/kurybiskos-linksmos-dovanos/teatrai-ir-filharmonija",
    "439": "https://www.geradovana.lt/superautomobiliai",
    "442": "https://www.geradovana.lt/zurnalu-prenumerata",
    "445": "https://www.geradovana.lt/superautomobiliai/lamborghini",
    "446": "https://www.geradovana.lt/superautomobiliai/tesla",
    "447": "https://www.geradovana.lt/superautomobiliai/ferrari",
    "448": "https://www.geradovana.lt/geras-skonis/pusryciai",
    "449": "https://www.geradovana.lt/tamsa",
    "450": "https://www.geradovana.lt/geras-skonis/pasaulio-virtuves",
    "452": "https://www.geradovana.lt/gerumo-dovanos",
    "456": "https://www.geradovana.lt/poilsis-su-nakvyne/poilsis-dvaruose-pilyse",
    "460": "https://www.geradovana.lt/spa-ir-masazai/spa-masazai-vilniuje",
    "461": "https://www.geradovana.lt/spa-ir-masazai/spa-masazai-kaune",
    "465": "https://www.geradovana.lt/poilsis-su-nakvyne/poilsis-anyksciuose",
    "468": "https://www.geradovana.lt/renginiai",
    "469": "https://www.geradovana.lt/poilsis-uzsienyje",
    "473": "https://www.geradovana.lt/poilsis-uzsienyje/poilsis-latvijoje",
    "476": "https://www.geradovana.lt/dovanos-uzsienyje/pramogos-latvijoje",
    "477": "https://www.geradovana.lt/poilsis-uzsienyje/pramogos-estijoje",
    "478": "https://www.geradovana.lt/poilsis-uzsienyje/pramogos-lenkijoje",
    "479": "https://www.geradovana.lt/miestu-korteles",
    "483": "https://www.geradovana.lt/kurybiskos-linksmos-dovanos/apsipirkimas-internetu",
    "484": "https://www.geradovana.lt/kurybiskos-linksmos-dovanos/zurnalai",
    "485": "https://www.geradovana.lt/geras-skonis/maistas-i-namus",
    "486": "https://www.geradovana.lt/kurybiskos-linksmos-dovanos/nuotoliniai-mokymai-ir-seminarai",
    "488": "https://www.geradovana.lt/poilsis-uzsienyje/kitos-salys",
    "489": "https://www.geradovana.lt/poilsis-su-nakvyne/poilsis-prie-ezero",
    "490": "https://www.geradovana.lt/poilsis-su-nakvyne/poilsis-prie-juros",
    "491": "https://www.geradovana.lt/aktyvios-pramogos/zygiai",
    "492": "https://www.geradovana.lt/auto-moto/bagiai",
    "493": "https://www.geradovana.lt/auto-moto/keturraciai",
    "494": "https://www.geradovana.lt/auto-moto/motociklai",
    "495": "https://www.geradovana.lt/aktyvios-pramogos/dazasvydis",
    "496": "https://www.geradovana.lt/aktyvios-pramogos/virtuali-realybe",
    "497": "https://www.geradovana.lt/poilsis-su-nakvyne/spa-poilsis",
    "499": "https://www.geradovana.lt/vandens-pramogos/irklentes",
    "500": "https://www.geradovana.lt/aktyvios-pramogos/sratasvydis",
    "501": "https://www.geradovana.lt/vandens-pramogos/vandens-batutai",
    "502": "https://www.geradovana.lt/vandens-pramogos/motociklai-vandens",
    "503": "https://www.geradovana.lt/grozis/dantu-balinimas",
    "507": "https://www.geradovana.lt/poilsis-su-nakvyne/poilsis-seimai",
    "511": "https://www.geradovana.lt/oro-pramogos/pilotavimo-pamokos",
    "512": "https://www.geradovana.lt/spa-ir-masazai/atpalaiduojantys-masazai",
    "513": "https://www.geradovana.lt/spa-ir-masazai/limfodrenaziniai-masazai",
    "514": "https://www.geradovana.lt/spa-ir-masazai/tailandietiski-masazai",
    "515": "https://www.geradovana.lt/spa-ir-masazai/masazai-ajurvediniai",
    "516": "https://www.geradovana.lt/spa-ir-masazai/masazai-nesciosioms",
    "517": "https://www.geradovana.lt/spa-ir-masazai/gydomieji-masazai",
    "518": "https://www.geradovana.lt/auto-moto/sportiniai-automobiliai",
    "519": "https://www.geradovana.lt/auto-moto/tankai",
    "520": "https://www.geradovana.lt/auto-moto/monster-truck",
    "521": "https://www.geradovana.lt/auto-moto/dzipai-safaris",
    "522": "https://www.geradovana.lt/auto-moto/dviraciai-paspirtukai",
    "523": "https://www.geradovana.lt/auto-moto/vairavimo-pamokos",
    "524": "https://www.geradovana.lt/vandens-pramogos/baseinai-pirtys",
    "525": "https://www.geradovana.lt/vandens-pramogos/valtys-vandens-dviraciai",
    "526": "https://www.geradovana.lt/vandens-pramogos/flyboard-pramogos",
    "527": "https://www.geradovana.lt/vandens-pramogos/kitos-vandens-pramogos",
    "528": "https://www.geradovana.lt/aktyvios-pramogos/kovos-menai",
    "529": "https://www.geradovana.lt/aktyvios-pramogos/laipiojimas",
    "530": "https://www.geradovana.lt/menai",
    "531": "https://www.geradovana.lt/kurybines-pramogos",
    "532": "https://www.geradovana.lt/kurybiskos-linksmos-dovanos/kvepalai-kosmetika",
    "533": "https://www.geradovana.lt/kurybiskos-linksmos-dovanos/sokiai-ir-muzika",
    "534": "https://www.geradovana.lt/geras-skonis/gerimu-degustacijos",
    "535": "https://www.geradovana.lt/geras-skonis/desertai",
    "536": "https://www.geradovana.lt/geras-skonis/restoranu-cekiai",
    "537": "https://www.geradovana.lt/kurybiskos-linksmos-dovanos/knygos",
    "538": "https://www.geradovana.lt/kurybiskos-linksmos-dovanos/muziejai",
    "539": "https://www.geradovana.lt/grozis/makiazas",
    "540": "https://www.geradovana.lt/grozis/grozio-mokymai",
    "546": "https://www.geradovana.lt/sveikatinimas/pluduriavimas",
    "547": "https://www.geradovana.lt/superautomobiliai/porsche",
    "549": "https://www.geradovana.lt/poilsis-su-nakvyne/darbostogos",
    "559": "https://www.geradovana.lt/auto-moto/pasivazinejimas-kabrioletu",
    "568": "https://www.geradovana.lt/geras-skonis/kavos-degustacijos",
    "569": "https://www.geradovana.lt/geras-skonis/sampano-degustacijos",
    "570": "https://www.geradovana.lt/geras-skonis/viskio-degustacijos",
    "571": "https://www.geradovana.lt/geras-skonis/vyno-degustacijos",
    "572": "https://www.geradovana.lt/geras-skonis/alaus-degustacijos",
    "573": "https://www.geradovana.lt/sveikatinimas/burnos-higiena",
    "575": "https://www.geradovana.lt/sveikatinimas/kraujo-ir-sveikatos-tyrimai",
    "577": "https://www.geradovana.lt/auto-moto/kitos-paslaugos",
    "581": "https://www.geradovana.lt/sveikatinimas/sveikatinimo-programos",
    "613": "https://www.geradovana.lt/sveikatinimas/jogos-uzsiemimai-ir-pamokos",
}
