"""Category catalog for LT - Generated from tree file."""

# Category ID to Name mapping
CATEGORY_NAME_MAP: dict[str, str] = {
    "203": "Karšti vasaros pasiūlymai",
    "229": "Vieta",
    "230": "Vilnius",
    "232": "Kaunas",
    "234": "Klaipėda",
    "236": "Panevėžys",
    "238": "Šiauliai",
    "240": "Druskininkai",
    "242": "Birštonas",
    "244": "Trakai",
    "246": "Palanga",
    "248": "Nida",
    "249": "Užsienis",
    "250": "Patirtis",
    "251": "Oro pramogos",
    "252": "Skrydis oro balionu",
    "253": "Šuolis parašiutu",
    "254": "Skrydis parasparniu",
    "255": "Apžvalginiai skrydžiai lėktuvu",
    "256": "Skrydis sklandytuvu",
    "257": "Vandens pramogos",
    "258": "Vandens parkai",
    "259": "Žvejyba",
    "260": "Plaukimas laivu ir jachta",
    "261": "Nardymas",
    "262": "Plaukimas baidare",
    "263": "Kaitavimas",
    "264": "Vandenlentės",
    "265": "Aktyvios pramogos",
    "266": "Šaudymas",
    "267": "Jodinėjimas",
    "268": "Auto / motopramogos",
    "269": "Kartingai",
    "270": "Pramogų parkai",
    "271": "Boulingas",
    "272": "Driftas",
    "273": "Grožis",
    "274": "Veido procedūros",
    "275": "Plaukų procedūros",
    "276": "Kūno procedūros",
    "277": "Grožio kompleksai",
    "278": "Manikiūras, pedikiūras",
    "279": "Procedūros vyrams",
    "280": "Poilsis Lietuvoje",
    "281": "Poilsis Druskininkuose",
    "282": "Poilsis Birštone",
    "283": "Poilsis Trakuose",
    "284": "Poilsis Palangoje",
    "285": "Poilsis Vilniuje",
    "286": "Poilsis Kaune",
    "287": "1 nakvynė",
    "288": "2 nakvynės",
    "289": "3 ir daugiau nakvynės",
    "290": "Poilsis dviem",
    "291": "Poilsis vienam",
    "292": "SPA ir masažai",
    "293": "SPA ir masažai dviem",
    "294": "Viso kūno masažai",
    "295": "Nugaros masažai",
    "296": "Masažų kompleksai",
    "297": "SPA procedūros",
    "298": "Masažai vyrams",
    "299": "Restoranai ir degustacijos",
    "300": "Vakarienė",
    "302": "Maisto degustacijos",
    "303": "Kulinarijos kursai",
    "304": "Kūrybiškos, linksmos",
    "305": "Fotosesijos",
    "306": "Žaidimai",
    "307": "Ekskursijos",
    "308": "Pamokos",
    "309": "Galvosūkių kambariai",
    "310": "Kinas",
    "311": "Sveikatinimas",
    "312": "Poilsis sanatorijoje",
    "313": "Sveikatinimo procedūros",
    "314": "TOP aktyvus laisvalaikis",
    "315": "Žiemos pramogos",
    "316": "Slidinėjimas",
    "317": "Gavėjas",
    "318": "Dovanos vyrams",
    "319": "Draugui",
    "320": "Vaikinui",
    "321": "Sutuoktiniui",
    "322": "Tėčiui",
    "323": "Seneliui",
    "324": "Broliui",
    "325": "Kolegai",
    "326": "Bosui",
    "327": "Sūnui",
    "328": "Dovanos moterims",
    "329": "Draugei",
    "330": "Merginai",
    "331": "Žmonai",
    "332": "Mamai",
    "333": "Močiutei",
    "334": "Sesei",
    "335": "Kolegei",
    "336": "Bosei",
    "337": "Dukrai",
    "338": "Dovanos dviem",
    "339": "Porai",
    "341": "Tėvams",
    "342": "Dovanos vaikams",
    "343": "Dovanos grupėms",
    "344": "Dovanos šeimai",
    "345": "Proga",
    "346": "Gimtadienis",
    "347": "Sužadėtuvės",
    "348": "Mergvakaris",
    "349": "Bernvakaris",
    "350": "Vestuvės",
    "351": "Vestuvių metinės",
    "352": "Krikštynos",
    "353": "Kalėdinės dovanos",
    "354": "Kalėdinės dovanos vyrams",
    "355": "Kalėdinės dovanos moterims",
    "356": "Kalėdinės dovanos dviem",
    "357": "Kalėdinės dovanos vaikams",
    "360": "Velykos",
    "362": "Rugsėjo 1 d.",
    "363": "Valentino dienos dovanos",
    "364": "Valentino dienos dovanos vyrams",
    "365": "Valentino dienos dovanos moterims",
    "366": "Valentino dienos dovanos dviem",
    "367": "Mamos diena",
    "368": "Tėvo diena",
    "369": "Moters diena",
    "370": "Mokyklos, universiteto baigimas",
    "371": "KITA",
    "374": "Naujausios dovanos",
    "375": "Dovanų rinkiniai",
    "376": "Parduotuvių dovanų čekiai",
    "377": "PC čekiai",
    "378": "Leidinių prenumeratos",
    "379": "Dovanų idėjos",
    "382": "Verslo dovanos",
    "383": "Tipas",
    "384": "Tik pas mus",
    "385": "Naujiena",
    "386": "TOP",
    "387": "1 asm.",
    "388": "2 asm.",
    "389": "3 asm.",
    "390": "1 naktis",
    "391": "2 naktys",
    "392": "3 naktys",
    "393": "4 naktys",
    "394": "5 naktys",
    "395": "6 naktys",
    "396": "7 naktys",
    "397": "8+ naktys",
    "398": "iki 30 min.",
    "399": "1 val.",
    "400": "1 val. 30 min.",
    "401": "2 val.",
    "402": "3 val.",
    "403": "3+ val.",
    "404": "Alytus",
    "405": "Anykščiai",
    "406": "Marijampolė",
    "407": "Telšiai",
    "408": "Tauragė",
    "409": "Utena",
    "410": "Molėtai",
    "416": "Asmenų skaičius",
    "417": "Naktų skaičius",
    "418": "Trukmė",
    "419": "45 min.",
    "420": "Visa Lietuva",
    "421": "Veido masažas",
    "422": "Pardavimų vietos",
    "429": "Golfas",
    "430": "Sportas, joga ir meditacija",
    "431": "Netrinti",
    "432": "Galvos masažai",
    "436": "Teatrai ir filharmonija",
    "438": "Caritas",
    "439": "Superautomobiliai",
    "442": "Žurnalų prenumerata",
    "443": "Prabangios dovanos",
    "444": "Joninės",
    "445": "Lamborghini",
    "446": "TESLA",
    "447": "Ferrari",
    "448": "Pusryčiai",
    "449": "Tamsa",
    "450": "Pasaulio virtuvės",
    "451": "Neribojama",
    "452": "Gerumo dovanos",
    "453": "R. Kaukėno paramos fondas",
    "456": "Poilsis dvaruose ir pilyse",
    "457": "1006 km lenktynės PALANGOJE",
    "458": "REDUCE RATING",
    "460": "Spa ir masažai Vilniuje",
    "461": "Spa ir masažai Kaune",
    "462": "30 min.",
    "463": "iki 1 val.",
    "464": "Visa diena",
    "465": "Poilsis Anykščiuose",
    "466": "iki 1 val. 30 min.",
    "467": "PromotionTOP",
    "468": "Renginiai",
    "469": "Poilsis užsienyje",
    "470": "Kita Virginijai",
    "471": "Dovanos senjorams",
    "472": "Dovanos nėštukėms",
    "473": "Poilsis Latvijoje",
    "474": "Maltiečiai (Maltos ordinas)",
    "475": "Gift of the day",
    "476": "Pramogos Latvijoje",
    "477": "Poilsis Estijoje",
    "478": "Poilsis Lenkijoje",
    "479": "Miestų kortelės",
    "480": "Dovanos su nuolaida",
    "482": "Pramogos namuose",
    "483": "Apsipirkimas internetu",
    "484": "Žurnalai",
    "485": "Maistas į namus",
    "486": "Nuotoliniai mokymai ir seminarai",
    "487": "Jau veikia",
    "488": "Kitos šalys",
    "489": "Poilsis prie ežero",
    "490": "Poilsis prie jūros",
    "491": "Žygiai",
    "492": "Bagiai",
    "493": "Keturračiai",
    "494": "Motociklai",
    "495": "Dažasvydis",
    "496": "Virtuali realybė",
    "497": "SPA poilsis",
    "499": "Irklentės / Sup",
    "500": "Šratasvydis",
    "501": "Vandens batutai",
    "502": "Vandens motociklai",
    "503": "Dantų balinimas",
    "504": "18 gimtadienio dovanos",
    "505": "16 gimtadienio dovanos",
    "506": "20 gimtadienio dovanos",
    "507": "Poilsis šeimai",
    "509": "Veikia",
    "511": "Pilotavimo pamoka",
    "512": "Atpalaiduojamieji masažai",
    "513": "Limfodrenažiniai masažai",
    "514": "Tailandietiški masažai",
    "515": "Ajurvediniai masažai",
    "516": "Masažai nėščiosioms",
    "517": "Gydomieji masažai",
    "518": "Sportiniai automobiliai",
    "519": "Tankai",
    "520": "Monster truck",
    "521": "Džipai ir safaris",
    "522": "Dviračiai ir paspirtukai",
    "523": "Vairavimo pamokos",
    "524": "Baseinai ir pirtys",
    "525": "Valtys ir vandens dviračiai",
    "526": "Flyboard",
    "527": "Kitos vandens pramogos",
    "528": "Kovos menai",
    "529": "Laipiojimas",
    "530": "Menai ir mokymai",
    "531": "Kūrybinės pramogos",
    "532": "Kvepalų ir kosmetikos kūrimas",
    "533": "Šokių ir muzikos pamokos",
    "534": "Gėrimų degustacijos",
    "535": "Desertai",
    "536": "Restoranų čekiai",
    "537": "Knygos",
    "538": "Muziejai",
    "539": "Makiažas",
    "540": "Grožio mokymai",
    "543": "Dovanos iki 5 €",
    "544": "Dovanos iki 10 €",
    "545": "Dovanos iki 20 €",
    "546": "Plūduriavimas",
    "547": "Porsche",
    "548": "Gimtadienio pasiūlymai",
    "549": "Darbostogos",
    "550": "Pagalba Ukrainai",
    "551": "Rezervacija internetu",
    "552": "Galiojimas",
    "553": "Savaitgalis",
    "554": "Darbo dienos",
    "555": "Visos dienos",
    "557": "Tėčio dienos nuolaida rinkiniams",
    "559": "Kabrioletai",
    "562": "Boso diena",
    "563": "Draugiški gyvūnams",
    "564": "Preview",
    "565": "Biržai",
    "566": "2,5 val.",
    "567": "Dovydas Karka rekomenduoja",
    "568": "Kavos degustacijos",
    "569": "Šampano degustacijos",
    "570": "Viskio degustacijos",
    "571": "Vyno degustacijos",
    "572": "Alaus degustacijos",
    "573": "Burnos higiena",
    "574": "Tyrimai",
    "575": "Kraujo ir sveikatos tyrimai",
    "576": "Dovanos mokytojams",
    "577": "Kitos paslaugos",
    "580": "Helovinas🦇",
    "581": "Sveikatinimo programos",
    "582": "10 min.",
    "583": "15 min",
    "584": "Iki 2 val.",
    "588": "Kupiškis",
    "589": "iki 10 min.",
    "590": "4 asm.",
    "591": "5+ asm.",
    "592": "Mažeikiai",
    "593": "Visas pasaulis",
    "594": "Specialūs vasaros pasiūlymai",
    "596": "Outlet",
    "597": "Kalėdines dovanos mamai",
    "598": "Kalėdines dovanos darbuotojams",
    "599": "Kalėdines verslo dovanos",
    "600": "Kaledinės dovanos berniukams",
    "601": "Kaledinės dovanos mergaitėms",
    "602": "Kalėdinės dovanos draugams",
    "603": "Kalėdinės dovanos mokytojai",
    "604": "Kalėdinės dovanos tėčiui",
    "605": "Kalėdinių dovanų rinkiniai",
    "606": "Kalėdinės dovanos seneliams",
    "607": "Kalėdinės dovanos tėvams",
    "608": "Kalėdinės dovanos paaugliams",
    "609": "Ribotas kiekis badge",
    "610": "Black Friday",
    "613": "Jogos užsiėmimai ir pamokos",
    "614": "Augintiniams",
    "615": "Šunų Kirpyklos",
    "616": "Kačių Kirpyklos",
    "617": "Veterinarijos Klinikos",
    "618": "Šunų Dresūra",
    "620": "Gera kaina",
    "621": "Dovanos paaugliams",
    "622": "Viešbučiai",
    "623": "Sodyba",
    "624": "Dvaras",
    "625": "Savaitgalio kelionė",
    "626": "Svečių namai",
    "627": "Apartamentai",
    "628": "Vienkiemis",
    "629": "Vila",
    "630": "Ranča",
    "631": "Vasarnamis",
    "632": "Sanatorijos",
    "633": "Kempingas",
    "634": "Poilsiavietė",
    "635": "Kaimo turizmo sodybos",
    "636": "Nameliai",
    "637": "Miško nameliai",
    "638": "Nameliai ant vandens",
    "639": "Namelis medyje",
    "640": "Jurtos",
    "641": "Glampingas",
    "642": "Restoranai",
    "643": "Japonų restoranas",
    "644": "Gruziniškas restoranas",
    "645": "Šeimos restoranas",
    "646": "Fine dining",
    "647": "Italų restoranas",
    "648": "Michelin restoranai",
    "649": "Sushi",
    "650": "Desertai",
    "651": "Maistas",
    "652": "Baras",
    "653": "Degustacijos",
    "655": "Vyno degustacija",
    "656": "Degustacinė vakarienė",
    "657": "Sporto klubas",
    "658": "Treniruotės",
    "659": "Boksas",
    "660": "Karatė",
    "661": "Dziudo",
    "662": "Aikido",
    "663": "Kikboksas",
    "665": "ledo arena / čiuožykla",
    "666": "Tenisas",
    "667": "Padelis",
    "668": "Stalo tenisas",
    "669": "Stalo tenisas",
    "670": "Biliardo žaidimai",
    "671": "Snukeris",
    "672": "Biliardas",
    "673": "Pulas",
    "674": "Airsoftai",
    "675": "Lazerių arena",
    "676": "Šaudymas iš lanko",
    "677": "Šokis",
    "678": "Badmintonas",
    "680": "Batutų parkas",
    "681": "Žirgynas",
    "682": "Mini golfas",
    "683": "Diskgolfas",
    "684": "Skvošas",
    "685": "Smiginis",
    "686": "Kerlingas",
    "687": "Vairavimas",
    "690": "Šarvuotis",
    "691": "Krosiniai motociklai",
    "692": "Off Road",
    "693": "Sniego motociklai",
    "694": "Grožio salonas / Grožio studija",
    "695": "Mezoterapija",
    "696": "Veido valymas",
    "697": "Presoterapija",
    "698": "Plaukų šalinimas lazeriu",
    "699": "Vandens dviratis",
    "700": "Akvaparkai",
    "701": "Baidarių nuoma",
    "702": "Kursai",
    "703": "Vairavimo mokyklos",
    "704": "Masažo kursai",
    "705": "Konditerijos kursai",
    "706": "Kursai internetu",
    "707": "Edukacijos",
    "708": "Grupinės treniruotės",
    "709": "Kursai suaugusiems",
    "710": "Kūrybinės dirbtuvės",
    "711": "Jojimo pamoka",
    "713": "Šokių pamokos",
    "714": "Dirbtuvės",
    "715": "Žvakių gamyba",
    "716": "Keramikos užsiėmimai",
    "718": "Sportinis masažas",
    "719": "Klasikinis masažas",
    "720": "Giliųjų audinių masažas",
    "721": "Švediškas masažas",
    "722": "Anticeliulitinis masažas",
    "724": "Kojų masažas",
    "725": "Masažai",
    "726": "Kobido",
    "727": "Rytietiški masažai",
    "728": "Ajurvedinis masažas",
    "729": "Taškinis masažas",
    "730": "Masažai dviems",
    "731": "Spa",
    "732": "Pirtis",
    "733": "Plūduriavimas",
    "734": "Dienos Spa",
    "735": "Spa centras",
    "736": "Plaukų Spa",
    "737": "Spa viešbutis",
}

# Category ID to URL mapping

# Category ID to URL mapping
CATEGORY_URL_MAP: dict[str, str] = {
    "203": "https://www.geradovana.lt/karsti-vasaros-pasiulymai",
    "229": "https://www.geradovana.lt/vieta",
    "230": "https://www.geradovana.lt/dovanos-vilniuje",
    "232": "https://www.geradovana.lt/dovanos-kaune",
    "234": "https://www.geradovana.lt/dovanos-klaipedoje",
    "236": "https://www.geradovana.lt/dovanos-panevezyje",
    "238": "https://www.geradovana.lt/dovanos-siauliuose",
    "240": "https://www.geradovana.lt/dovanos-druskininkuose",
    "242": "https://www.geradovana.lt/dovanos-birstone",
    "244": "https://www.geradovana.lt/dovanos-trakuose",
    "246": "https://www.geradovana.lt/dovanos-palangoje",
    "248": "https://www.geradovana.lt/dovanos-nidoje",
    "249": "https://www.geradovana.lt/dovanos-uzsienyje",
    "250": "https://www.geradovana.lt/patirtis",
    "251": "https://www.geradovana.lt/oro-pramogos",
    "252": "https://www.geradovana.lt/oro-pramogos/skrydis-oro-balionu",
    "253": "https://www.geradovana.lt/oro-pramogos/suolis-parasiutu",
    "254": "https://www.geradovana.lt/oro-pramogos/skrydis-parasparniu",
    "255": "https://www.geradovana.lt/oro-pramogos/apzvalginiai-skrydziai-lektuvu",
    "256": "https://www.geradovana.lt/oro-pramogos/skrydis-sklandytuvu",
    "257": "https://www.geradovana.lt/vandens-pramogos",
    "258": "https://www.geradovana.lt/vandens-pramogos/vandens-parkai",
    "259": "https://www.geradovana.lt/vandens-pramogos/zvejyba",
    "260": "https://www.geradovana.lt/vandens-pramogos/plaukimas-laivu-ir-jachta",
    "261": "https://www.geradovana.lt/vandens-pramogos/nardymas",
    "262": "https://www.geradovana.lt/vandens-pramogos/plaukimas-baidare",
    "263": "https://www.geradovana.lt/vandens-pramogos/kaitavimas",
    "264": "https://www.geradovana.lt/vandens-pramogos/vandenlentes",
    "265": "https://www.geradovana.lt/aktyvios-pramogos",
    "266": "https://www.geradovana.lt/aktyvios-pramogos/saudymas",
    "267": "https://www.geradovana.lt/aktyvios-pramogos/jodinejimas",
    "268": "https://www.geradovana.lt/auto-moto",
    "269": "https://www.geradovana.lt/auto-moto/kartingai",
    "270": "https://www.geradovana.lt/aktyvios-pramogos/nuotykiu-parkai",
    "271": "https://www.geradovana.lt/aktyvios-pramogos/boulingas",
    "272": "https://www.geradovana.lt/auto-moto/driftas",
    "273": "https://www.geradovana.lt/grozis",
    "274": "https://www.geradovana.lt/grozis/veido-proceduros",
    "275": "https://www.geradovana.lt/grozis/plauku-proceduros",
    "276": "https://www.geradovana.lt/grozis/kuno-proceduros",
    "277": "https://www.geradovana.lt/grozis/grozio-kompleksai",
    "278": "https://www.geradovana.lt/grozis/manikiuras-pedikiuras",
    "279": "https://www.geradovana.lt/grozis/proceduros-vyrams",
    "280": "https://www.geradovana.lt/poilsis-su-nakvyne",
    "281": "https://www.geradovana.lt/poilsis-su-nakvyne/poilsis-druskininkuose",
    "282": "https://www.geradovana.lt/poilsis-su-nakvyne/poilsis-birstone",
    "283": "https://www.geradovana.lt/poilsis-su-nakvyne/poilsis-trakuose",
    "284": "https://www.geradovana.lt/poilsis-su-nakvyne/poilsis-palangoje",
    "285": "https://www.geradovana.lt/poilsis-su-nakvyne/poilsis-vilniuje",
    "286": "https://www.geradovana.lt/poilsis-su-nakvyne/poilsis-kaune",
    "287": "https://www.geradovana.lt/poilsis-su-nakvyne/1-nakvyne",
    "288": "https://www.geradovana.lt/poilsis-su-nakvyne/2-nakvynes",
    "289": "https://www.geradovana.lt/poilsis-su-nakvyne/3-ir-daugiau-nakvynes",
    "290": "https://www.geradovana.lt/poilsis-su-nakvyne/2-asmenims",
    "291": "https://www.geradovana.lt/poilsis-su-nakvyne/1-asmeniui",
    "292": "https://www.geradovana.lt/spa-ir-masazai",
    "293": "https://www.geradovana.lt/spa-ir-masazai/spa-ir-masazai-dviem",
    "294": "https://www.geradovana.lt/spa-ir-masazai/viso-kuno-masazai",
    "295": "https://www.geradovana.lt/spa-ir-masazai/nugaros-masazai",
    "296": "https://www.geradovana.lt/spa-ir-masazai/masazu-kompleksai",
    "297": "https://www.geradovana.lt/spa-ir-masazai/spa-proceduros",
    "298": "https://www.geradovana.lt/spa-ir-masazai/masazai-vyrams",
    "299": "https://www.geradovana.lt/geras-skonis",
    "300": "https://www.geradovana.lt/geras-skonis/vakariene",
    "302": "https://www.geradovana.lt/geras-skonis/degustacijos",
    "303": "https://www.geradovana.lt/geras-skonis/kursai",
    "304": "https://www.geradovana.lt/kurybiskos-linksmos-dovanos",
    "305": "https://www.geradovana.lt/kurybiskos-linksmos-dovanos/fotosesijos",
    "306": "https://www.geradovana.lt/aktyvios-pramogos/zaidimai",
    "307": "https://www.geradovana.lt/kurybiskos-linksmos-dovanos/ekskursijos",
    "308": "https://www.geradovana.lt/kurybiskos-linksmos-dovanos/pamokos",
    "309": "https://www.geradovana.lt/aktyvios-pramogos/galvosukiu-kambariai",
    "310": "https://www.geradovana.lt/kurybiskos-linksmos-dovanos/kinas",
    "311": "https://www.geradovana.lt/sveikatinimas",
    "312": "https://www.geradovana.lt/poilsis-su-nakvyne/poilsis-sanatorijoje",
    "313": "https://www.geradovana.lt/sveikatinimas/sveikatinimo-proceduros",
    "314": "https://www.geradovana.lt/top-aktyvus-laisvalaikis",
    "315": "https://www.geradovana.lt/ziemos-pramogos",
    "316": "https://www.geradovana.lt/ziemos-pramogos/slidinejimas",
    "317": "https://www.geradovana.lt/Gavejas",
    "318": "https://www.geradovana.lt/dovanos-vyrams",
    "319": "https://www.geradovana.lt/dovanos-vyrams/dovanos-draugui",
    "320": "https://www.geradovana.lt/dovanos-vyrams/dovanos-vaikinui",
    "321": "https://www.geradovana.lt/dovanos-vyrams/dovanos-sutuoktiniui",
    "322": "https://www.geradovana.lt/dovanos-vyrams/dovanos-teciui",
    "323": "https://www.geradovana.lt/dovanos-vyrams/dovanos-seneliui",
    "324": "https://www.geradovana.lt/dovanos-vyrams/dovanos-broliui",
    "325": "https://www.geradovana.lt/dovanos-vyrams/dovanos-kolegai",
    "326": "https://www.geradovana.lt/dovanos-vyrams/dovanos-bosui",
    "327": "https://www.geradovana.lt/dovanos-vyrams/dovanos-sunui",
    "328": "https://www.geradovana.lt/dovanos-moterims",
    "329": "https://www.geradovana.lt/dovanos-moterims/dovanos-draugei",
    "330": "https://www.geradovana.lt/dovanos-moterims/dovanos-merginai",
    "331": "https://www.geradovana.lt/dovanos-moterims/dovanos-zmonai",
    "332": "https://www.geradovana.lt/dovanos-moterims/dovanos-mamai",
    "333": "https://www.geradovana.lt/dovanos-moterims/dovanos-mociutei",
    "334": "https://www.geradovana.lt/dovanos-moterims/dovanos-sesei",
    "335": "https://www.geradovana.lt/dovanos-moterims/dovanos-kolegei",
    "336": "https://www.geradovana.lt/dovanos-moterims/dovanos-bosei",
    "337": "https://www.geradovana.lt/dovanos-moterims/dovanos-dukrai",
    "338": "https://www.geradovana.lt/dovanos-dviem",
    "339": "https://www.geradovana.lt/dovanos-dviem/dovanos-porai",
    "341": "https://www.geradovana.lt/dovanos-dviem/dovanos-tevams",
    "342": "https://www.geradovana.lt/dovanos-vaikams",
    "343": "https://www.geradovana.lt/dovanos-grupems",
    "344": "https://www.geradovana.lt/dovanos-seimai",
    "345": "https://www.geradovana.lt/proga",
    "346": "https://www.geradovana.lt/gimtadienio-dovanos",
    "347": "https://www.geradovana.lt/suzadetuviu-dovanos",
    "348": "https://www.geradovana.lt/mergvakario-dovanos",
    "349": "https://www.geradovana.lt/bernvakario-dovanos",
    "350": "https://www.geradovana.lt/vestuviu-dovanos",
    "351": "https://www.geradovana.lt/vestuviu-metiniu-dovanos",
    "352": "https://www.geradovana.lt/krikstynu-dovanos",
    "353": "https://www.geradovana.lt/kaledines-dovanos",
    "354": "https://www.geradovana.lt/kaledines-dovanos/vyrams",
    "355": "https://www.geradovana.lt/kaledines-dovanos/moterims",
    "356": "https://www.geradovana.lt/kaledines-dovanos/dviem",
    "357": "https://www.geradovana.lt/kaledines-dovanos/vaikams",
    "360": "https://www.geradovana.lt/velykos",
    "362": "https://www.geradovana.lt/rugsejo-1-d-dovanos",
    "363": "https://www.geradovana.lt/valentino-dienos-dovanos",
    "364": "https://www.geradovana.lt/valentino-dienos-dovanos/valentino-dienos-dovanos-vyrams",
    "365": "https://www.geradovana.lt/valentino-dienos-dovanos/valentino-dienos-dovanos-moterims",
    "366": "https://www.geradovana.lt/valentino-dienos-dovanos/valentino-dienos-dovanos-dviems",
    "367": "https://www.geradovana.lt/mamos-diena",
    "368": "https://www.geradovana.lt/tevo-dienos-dovanos",
    "369": "https://www.geradovana.lt/moters-dienos-dovanos",
    "370": "https://www.geradovana.lt/mokyklos-universiteto-baigimo-dovanos",
    "371": "https://www.geradovana.lt/kita",
    "374": "https://www.geradovana.lt/naujausios-dovanos",
    "375": "https://www.geradovana.lt/dovanu-rinkiniai",
    "376": "https://www.geradovana.lt/parduotuviu-dovanu-cekiai",
    "377": "https://www.geradovana.lt/pc-cekiai",
    "378": "https://www.geradovana.lt/leidiniu-prenumeratos",
    "379": "https://www.geradovana.lt/dovanu-idejos",
    "382": "https://www.geradovana.lt/dovanos-verslui",
    "383": "https://www.geradovana.lt/tipas",
    "384": "https://www.geradovana.lt/tik-pas-mus",
    "385": "https://www.geradovana.lt/naujiena",
    "386": "https://www.geradovana.lt/top",
    "387": "https://www.geradovana.lt/1-asm",
    "388": "https://www.geradovana.lt/2-asm",
    "389": "https://www.geradovana.lt/3-asm",
    "390": "https://www.geradovana.lt/1-naktis",
    "391": "https://www.geradovana.lt/2-naktys",
    "392": "https://www.geradovana.lt/3-naktys",
    "393": "https://www.geradovana.lt/4-naktys",
    "394": "https://www.geradovana.lt/5-naktys",
    "395": "https://www.geradovana.lt/6-naktys",
    "396": "https://www.geradovana.lt/7-naktys",
    "397": "https://www.geradovana.lt/8-naktys",
    "398": "https://www.geradovana.lt/iki-30-min",
    "399": "https://www.geradovana.lt/1-val",
    "400": "https://www.geradovana.lt/15-val",
    "401": "https://www.geradovana.lt/2-val",
    "402": "https://www.geradovana.lt/3-val",
    "403": "https://www.geradovana.lt/3-ir-ilgiau",
    "404": "https://www.geradovana.lt/dovanos-alytuje",
    "405": "https://www.geradovana.lt/dovanos-anyksciuose",
    "406": "https://www.geradovana.lt/dovanos-marijampoleje",
    "407": "https://www.geradovana.lt/dovanos-telsiuose",
    "408": "https://www.geradovana.lt/dovanos-taurageje",
    "409": "https://www.geradovana.lt/dovanos-utenoje",
    "410": "https://www.geradovana.lt/dovanos-moletuose",
    "416": "https://www.geradovana.lt/Asmenu-skaicius",
    "417": "https://www.geradovana.lt/Naktu-skaicius",
    "418": "https://www.geradovana.lt/Trukme",
    "419": "https://www.geradovana.lt/45-min",
    "420": "https://www.geradovana.lt/visa-lietuva",
    "421": "https://www.geradovana.lt/spa-ir-masazai/veido-masazas",
    "422": "https://www.geradovana.lt/pardavimu-vietos",
    "429": "https://www.geradovana.lt/aktyvios-pramogos/golfas",
    "430": "https://www.geradovana.lt/sveikatinimas/sporto-uzsiemimai",
    "431": "https://www.geradovana.lt/netrinti",
    "432": "https://www.geradovana.lt/spa-ir-masazai/galvos-masazai",
    "436": "https://www.geradovana.lt/kurybiskos-linksmos-dovanos/teatrai-ir-filharmonija",
    "438": "https://www.geradovana.lt/gerumo-dovanos/caritas",
    "439": "https://www.geradovana.lt/superautomobiliai",
    "442": "https://www.geradovana.lt/zurnalu-prenumerata",
    "443": "https://www.geradovana.lt/prabangios-dovanos",
    "444": "https://www.geradovana.lt/jonines",
    "445": "https://www.geradovana.lt/superautomobiliai/lamborghini",
    "446": "https://www.geradovana.lt/superautomobiliai/tesla",
    "447": "https://www.geradovana.lt/superautomobiliai/ferrari",
    "448": "https://www.geradovana.lt/geras-skonis/pusryciai",
    "449": "https://www.geradovana.lt/tamsa",
    "450": "https://www.geradovana.lt/geras-skonis/pasaulio-virtuves",
    "451": "https://www.geradovana.lt/neribojama",
    "452": "https://www.geradovana.lt/gerumo-dovanos",
    "453": "https://www.geradovana.lt/gerumo-dovanos/r-kaukeno-paramos-fondas",
    "456": "https://www.geradovana.lt/poilsis-su-nakvyne/poilsis-dvaruose-pilyse",
    "457": "https://www.geradovana.lt/1006-km-lenktynes-palangoje",
    "458": "https://www.geradovana.lt/reduce-rating",
    "460": "https://www.geradovana.lt/spa-ir-masazai/spa-masazai-vilniuje",
    "461": "https://www.geradovana.lt/spa-ir-masazai/spa-masazai-kaune",
    "462": "https://www.geradovana.lt/30-min",
    "463": "https://www.geradovana.lt/iki-1-val",
    "464": "https://www.geradovana.lt/visa-diena",
    "465": "https://www.geradovana.lt/poilsis-su-nakvyne/poilsis-anyksciuose",
    "466": "https://www.geradovana.lt/iki-15-val",
    "467": "https://www.geradovana.lt/promotiontop",
    "468": "https://www.geradovana.lt/renginiai",
    "469": "https://www.geradovana.lt/poilsis-uzsienyje",
    "470": "https://www.geradovana.lt/kita-virginijai",
    "471": "https://www.geradovana.lt/dovanos-senjorams",
    "472": "https://www.geradovana.lt/dovanos-nestukems",
    "473": "https://www.geradovana.lt/poilsis-uzsienyje/poilsis-latvijoje",
    "474": "https://www.geradovana.lt/gerumo-dovanos/maltieciai-maltos-ordinas",
    "475": "https://www.geradovana.lt/gift-of-the-day",
    "476": "https://www.geradovana.lt/dovanos-uzsienyje/pramogos-latvijoje",
    "477": "https://www.geradovana.lt/poilsis-uzsienyje/pramogos-estijoje",
    "478": "https://www.geradovana.lt/poilsis-uzsienyje/pramogos-lenkijoje",
    "479": "https://www.geradovana.lt/miestu-korteles",
    "480": "https://www.geradovana.lt/nuolaidos",
    "482": "https://www.geradovana.lt/pramogos-is-namu",
    "483": "https://www.geradovana.lt/kurybiskos-linksmos-dovanos/apsipirkimas-internetu",
    "484": "https://www.geradovana.lt/kurybiskos-linksmos-dovanos/zurnalai",
    "485": "https://www.geradovana.lt/geras-skonis/maistas-i-namus",
    "486": "https://www.geradovana.lt/kurybiskos-linksmos-dovanos/nuotoliniai-mokymai-ir-seminarai",
    "487": "https://www.geradovana.lt/jau-veikia",
    "488": "https://www.geradovana.lt/poilsis-uzsienyje/kitos-salys",
    "489": "https://www.geradovana.lt/poilsis-su-nakvyne/poilsis-prie-ezero",
    "490": "https://www.geradovana.lt/poilsis-su-nakvyne/poilsis-prie-juros",
    "491": "https://www.geradovana.lt/aktyvios-pramogos/zygiai",
    "492": "https://www.geradovana.lt/auto-moto/bagiai",
    "493": "https://www.geradovana.lt/auto-moto/keturraciai",
    "494": "https://www.geradovana.lt/auto-moto/motociklai",
    "495": "https://www.geradovana.lt/aktyvios-pramogos/dazasvydis",
    "496": "https://www.geradovana.lt/aktyvios-pramogos/virtuali-realybe",
    "497": "https://www.geradovana.lt/poilsis-su-nakvyne/spa-poilsis",
    "499": "https://www.geradovana.lt/vandens-pramogos/irklentes",
    "500": "https://www.geradovana.lt/aktyvios-pramogos/sratasvydis",
    "501": "https://www.geradovana.lt/vandens-pramogos/vandens-batutai",
    "502": "https://www.geradovana.lt/vandens-pramogos/motociklai-vandens",
    "503": "https://www.geradovana.lt/grozis/dantu-balinimas",
    "504": "https://www.geradovana.lt/gimtadienio-dovanos/18-gimtadienio-dovanos",
    "505": "https://www.geradovana.lt/gimtadienio-dovanos/16-gimtadienio-dovanos",
    "506": "https://www.geradovana.lt/gimtadienio-dovanos/20-gimtadienio-dovanos",
    "507": "https://www.geradovana.lt/poilsis-su-nakvyne/poilsis-seimai",
    "509": "https://www.geradovana.lt/veikia",
    "511": "https://www.geradovana.lt/oro-pramogos/pilotavimo-pamokos",
    "512": "https://www.geradovana.lt/spa-ir-masazai/atpalaiduojantys-masazai",
    "513": "https://www.geradovana.lt/spa-ir-masazai/limfodrenaziniai-masazai",
    "514": "https://www.geradovana.lt/spa-ir-masazai/tailandietiski-masazai",
    "515": "https://www.geradovana.lt/spa-ir-masazai/masazai-ajurvediniai",
    "516": "https://www.geradovana.lt/spa-ir-masazai/masazai-nesciosioms",
    "517": "https://www.geradovana.lt/spa-ir-masazai/gydomieji-masazai",
    "518": "https://www.geradovana.lt/auto-moto/sportiniai-automobiliai",
    "519": "https://www.geradovana.lt/auto-moto/tankai",
    "520": "https://www.geradovana.lt/auto-moto/monster-truck",
    "521": "https://www.geradovana.lt/auto-moto/dzipai-safaris",
    "522": "https://www.geradovana.lt/auto-moto/dviraciai-paspirtukai",
    "523": "https://www.geradovana.lt/auto-moto/vairavimo-pamokos",
    "524": "https://www.geradovana.lt/vandens-pramogos/baseinai-pirtys",
    "525": "https://www.geradovana.lt/vandens-pramogos/valtys-vandens-dviraciai",
    "526": "https://www.geradovana.lt/vandens-pramogos/flyboard-pramogos",
    "527": "https://www.geradovana.lt/vandens-pramogos/kitos-vandens-pramogos",
    "528": "https://www.geradovana.lt/aktyvios-pramogos/kovos-menai",
    "529": "https://www.geradovana.lt/aktyvios-pramogos/laipiojimas",
    "530": "https://www.geradovana.lt/menai",
    "531": "https://www.geradovana.lt/kurybines-pramogos",
    "532": "https://www.geradovana.lt/kurybiskos-linksmos-dovanos/kvepalai-kosmetika",
    "533": "https://www.geradovana.lt/kurybiskos-linksmos-dovanos/sokiai-ir-muzika",
    "534": "https://www.geradovana.lt/geras-skonis/gerimu-degustacijos",
    "535": "https://www.geradovana.lt/geras-skonis/desertai",
    "536": "https://www.geradovana.lt/geras-skonis/restoranu-cekiai",
    "537": "https://www.geradovana.lt/kurybiskos-linksmos-dovanos/knygos",
    "538": "https://www.geradovana.lt/kurybiskos-linksmos-dovanos/muziejai",
    "539": "https://www.geradovana.lt/grozis/makiazas",
    "540": "https://www.geradovana.lt/grozis/grozio-mokymai",
    "543": "https://www.geradovana.lt/dovanos-iki-5",
    "544": "https://www.geradovana.lt/dovanos-iki-10",
    "545": "https://www.geradovana.lt/dovanos-iki-20",
    "546": "https://www.geradovana.lt/sveikatinimas/pluduriavimas",
    "547": "https://www.geradovana.lt/superautomobiliai/porsche",
    "548": "https://www.geradovana.lt/gimtadienio-pasiulymai",
    "549": "https://www.geradovana.lt/poilsis-su-nakvyne/darbostogos",
    "550": "https://www.geradovana.lt/pagalba-ukrainai",
    "551": "https://www.geradovana.lt/rezervacija-internetu",
    "552": "https://www.geradovana.lt/galiojimas",
    "553": "https://www.geradovana.lt/savaitgalis",
    "554": "https://www.geradovana.lt/darbo-dienos",
    "555": "https://www.geradovana.lt/visos-dienos",
    "557": "https://www.geradovana.lt/tecio-dienos-nuolaida-rinkiniams",
    "559": "https://www.geradovana.lt/auto-moto/pasivazinejimas-kabrioletu",
    "562": "https://www.geradovana.lt/boso-diena",
    "563": "https://www.geradovana.lt/draugiski-gyvunams",
    "564": "https://www.geradovana.lt/preview",
    "565": "https://www.geradovana.lt/birzai",
    "566": "https://www.geradovana.lt/2,5val",
    "567": "https://www.geradovana.lt/dovydas-karka-rekomenduoja",
    "568": "https://www.geradovana.lt/geras-skonis/kavos-degustacijos",
    "569": "https://www.geradovana.lt/geras-skonis/sampano-degustacijos",
    "570": "https://www.geradovana.lt/geras-skonis/viskio-degustacijos",
    "571": "https://www.geradovana.lt/geras-skonis/vyno-degustacijos",
    "572": "https://www.geradovana.lt/geras-skonis/alaus-degustacijos",
    "573": "https://www.geradovana.lt/sveikatinimas/burnos-higiena",
    "574": "https://www.geradovana.lt/tyrimai",
    "575": "https://www.geradovana.lt/sveikatinimas/kraujo-ir-sveikatos-tyrimai",
    "576": "https://www.geradovana.lt/dovanos-mokytojams-aukletojams",
    "577": "https://www.geradovana.lt/auto-moto/kitos-paslaugos",
    "580": "https://www.geradovana.lt/helovino-pramogos",
    "581": "https://www.geradovana.lt/sveikatinimas/sveikatinimo-programos",
    "582": "https://www.geradovana.lt/10-min",
    "583": "https://www.geradovana.lt/min-15",
    "584": "https://www.geradovana.lt/iki-2-val",
    "588": "https://www.geradovana.lt/kupiskis",
    "589": "https://www.geradovana.lt/iki-10-min",
    "590": "https://www.geradovana.lt/4-asm",
    "591": "https://www.geradovana.lt/5-asm",
    "592": "https://www.geradovana.lt/mazeikiai",
    "593": "https://www.geradovana.lt/visas-pasaulis",
    "594": "https://www.geradovana.lt/vasaros-pasiulymai",
    "596": "https://www.geradovana.lt/outlet",
    "597": "https://www.geradovana.lt/kaledines-dovanos/tevams/mamai",
    "598": "https://www.geradovana.lt/kaledines-dovanos/verslo/darbuotojams",
    "599": "https://www.geradovana.lt/kaledines-dovanos/verslo",
    "600": "https://www.geradovana.lt/kaledines-dovanos/vaikams/berniukams",
    "601": "https://www.geradovana.lt/kaledines-dovanos/vaikams/mergaitems",
    "602": "https://www.geradovana.lt/kaledines-dovanos/draugams",
    "603": "https://www.geradovana.lt/kaledines-dovanos/mokytojai",
    "604": "https://www.geradovana.lt/kaledines-dovanos/tevams/teciui",
    "605": "https://www.geradovana.lt/kaledines-dovanos/rinkiniai",
    "606": "https://www.geradovana.lt/kaledines-dovanos/seneliams",
    "607": "https://www.geradovana.lt/kaledines-dovanos/tevams",
    "608": "https://www.geradovana.lt/kaledines-dovanos/paaugliams",
    "609": "https://www.geradovana.lt/ribotas-kiekis-badge",
    "610": "https://www.geradovana.lt/black-friday",
    "613": "https://www.geradovana.lt/sveikatinimas/jogos-uzsiemimai-ir-pamokos",
    "614": "https://www.geradovana.lt/augintiniams",
    "615": "https://www.geradovana.lt/augintiniams/sunu-kirpyklos",
    "616": "https://www.geradovana.lt/augintiniams/kaciu-kirpyklos",
    "617": "https://www.geradovana.lt/augintiniams/veterinarijos-klinikos",
    "618": "https://www.geradovana.lt/augintiniams/sunu-dresura",
    "620": "https://www.geradovana.lt/gera-kaina",
    "621": "https://www.geradovana.lt/dovanos-paaugliams",
    "622": "https://www.geradovana.lt/poilsis-su-nakvyne/viesbuciai",
    "623": "https://www.geradovana.lt/poilsis-su-nakvyne/sodyba",
    "624": "https://www.geradovana.lt/poilsis-su-nakvyne/dvaras",
    "625": "https://www.geradovana.lt/poilsis-su-nakvyne/savaitgalio-kelione",
    "626": "https://www.geradovana.lt/poilsis-su-nakvyne/sveciu-namai",
    "627": "https://www.geradovana.lt/poilsis-su-nakvyne/apartamentai",
    "628": "https://www.geradovana.lt/poilsis-su-nakvyne/vienkiemis",
    "629": "https://www.geradovana.lt/poilsis-su-nakvyne/vila",
    "630": "https://www.geradovana.lt/poilsis-su-nakvyne/ranca",
    "631": "https://www.geradovana.lt/poilsis-su-nakvyne/vasarnamis",
    "632": "https://www.geradovana.lt/poilsis-su-nakvyne/sanatorijos",
    "633": "https://www.geradovana.lt/poilsis-su-nakvyne/kempingas",
    "634": "https://www.geradovana.lt/poilsis-su-nakvyne/poilsiaviete",
    "635": "https://www.geradovana.lt/poilsis-su-nakvyne/kaimo-turizmo-sodybos",
    "636": "https://www.geradovana.lt/poilsis-su-nakvyne/nameliai",
    "637": "https://www.geradovana.lt/poilsis-su-nakvyne/misko-nameliai",
    "638": "https://www.geradovana.lt/poilsis-su-nakvyne/nameliai-ant-vandens",
    "639": "https://www.geradovana.lt/poilsis-su-nakvyne/namelis-medyje",
    "640": "https://www.geradovana.lt/poilsis-su-nakvyne/jurtos",
    "641": "https://www.geradovana.lt/poilsis-su-nakvyne/glampingas",
    "642": "https://www.geradovana.lt/geras-skonis/restoranai",
    "643": "https://www.geradovana.lt/geras-skonis/japonu-restoranas",
    "644": "https://www.geradovana.lt/geras-skonis/gruziniskas-restoranas",
    "645": "https://www.geradovana.lt/geras-skonis/seimos-restoranas",
    "646": "https://www.geradovana.lt/geras-skonis/fine-dining",
    "647": "https://www.geradovana.lt/geras-skonis/italu-restoranas",
    "648": "https://www.geradovana.lt/geras-skonis/michelin-restoranai",
    "649": "https://www.geradovana.lt/geras-skonis/sushi",
    "650": "https://www.geradovana.lt/geras-skonis/desertai",
    "651": "https://www.geradovana.lt/geras-skonis/maistas",
    "652": "https://www.geradovana.lt/geras-skonis/baras",
    "653": "https://www.geradovana.lt/geras-skonis/degustacijos",
    "655": "https://www.geradovana.lt/geras-skonis/vyno-degustacija",
    "656": "https://www.geradovana.lt/geras-skonis/degustacine-vakariene",
    "657": "https://www.geradovana.lt/aktyvios-pramogos/sporto-klubas",
    "658": "https://www.geradovana.lt/aktyvios-pramogos/treniruotes",
    "659": "https://www.geradovana.lt/aktyvios-pramogos/boksas",
    "660": "https://www.geradovana.lt/aktyvios-pramogos/karate",
    "661": "https://www.geradovana.lt/aktyvios-pramogos/dziudo",
    "662": "https://www.geradovana.lt/aktyvios-pramogos/aikido",
    "663": "https://www.geradovana.lt/aktyvios-pramogos/kikboksas",
    "665": "https://www.geradovana.lt/aktyvios-pramogos/ledo-arena-ciuozykla",
    "666": "https://www.geradovana.lt/aktyvios-pramogos/tenisas",
    "667": "https://www.geradovana.lt/aktyvios-pramogos/padelis",
    "668": "https://www.geradovana.lt/aktyvios-pramogos/stalo-tenisas",
    "669": "https://www.geradovana.lt/aktyvios-pramogos/stalo-tenisas",
    "670": "https://www.geradovana.lt/aktyvios-pramogos/biliardo-zaidimai",
    "671": "https://www.geradovana.lt/aktyvios-pramogos/snukeris",
    "672": "https://www.geradovana.lt/aktyvios-pramogos/biliardas",
    "673": "https://www.geradovana.lt/aktyvios-pramogos/pulas",
    "674": "https://www.geradovana.lt/aktyvios-pramogos/airsoftai",
    "675": "https://www.geradovana.lt/aktyvios-pramogos/lazeriu-arena",
    "676": "https://www.geradovana.lt/aktyvios-pramogos/saudymas-is-lanko",
    "677": "https://www.geradovana.lt/aktyvios-pramogos/sokis",
    "678": "https://www.geradovana.lt/aktyvios-pramogos/badmintonas",
    "680": "https://www.geradovana.lt/aktyvios-pramogos/batutu-parkas",
    "681": "https://www.geradovana.lt/aktyvios-pramogos/zirgynas",
    "682": "https://www.geradovana.lt/aktyvios-pramogos/mini-golfas",
    "683": "https://www.geradovana.lt/aktyvios-pramogos/diskgolfas",
    "684": "https://www.geradovana.lt/aktyvios-pramogos/skvosas",
    "685": "https://www.geradovana.lt/aktyvios-pramogos/smiginis",
    "686": "https://www.geradovana.lt/aktyvios-pramogos/kerlingas",
    "687": "https://www.geradovana.lt/auto-moto/vairavimas",
    "690": "https://www.geradovana.lt/auto-moto/sarvuotis",
    "691": "https://www.geradovana.lt/auto-moto/krosiniai-motociklai",
    "692": "https://www.geradovana.lt/auto-moto/off-road",
    "693": "https://www.geradovana.lt/auto-moto/sniego-motociklai",
    "694": "https://www.geradovana.lt/grozis/grozio-salonas-grozio-studija",
    "695": "https://www.geradovana.lt/grozis/mezoterapija",
    "696": "https://www.geradovana.lt/grozis/veido-valymas",
    "697": "https://www.geradovana.lt/grozis/presoterapija",
    "698": "https://www.geradovana.lt/grozis/plauku-salinimas-lazeriu",
    "699": "https://www.geradovana.lt/vandens-pramogos/vandens-dviratis",
    "700": "https://www.geradovana.lt/vandens-pramogos/akvaparkai",
    "701": "https://www.geradovana.lt/vandens-pramogos/baidariu-nuoma",
    "702": "https://www.geradovana.lt/kursai",
    "703": "https://www.geradovana.lt/kursai/vairavimo-mokyklos",
    "704": "https://www.geradovana.lt/kursai/masazo-kursai",
    "705": "https://www.geradovana.lt/kursai/konditerijos-kursai",
    "706": "https://www.geradovana.lt/kursai/kursai-internetu",
    "707": "https://www.geradovana.lt/kursai/edukacijos",
    "708": "https://www.geradovana.lt/kursai/grupines-treniruotes",
    "709": "https://www.geradovana.lt/kursai/kursai-suaugusiems",
    "710": "https://www.geradovana.lt/kursai/kurybines-dirbtuves",
    "711": "https://www.geradovana.lt/kursai/jojimo-pamoka",
    "713": "https://www.geradovana.lt/kursai/sokiu-pamokos",
    "714": "https://www.geradovana.lt/kursai/dirbtuves",
    "715": "https://www.geradovana.lt/kursai/zvakiu-gamyba",
    "716": "https://www.geradovana.lt/kursai/keramikos-uzsiemimai",
    "718": "https://www.geradovana.lt/spa-ir-masazai/sportinis-masazas",
    "719": "https://www.geradovana.lt/spa-ir-masazai/klasikinis-masazas",
    "720": "https://www.geradovana.lt/spa-ir-masazai/giliuju-audiniu-masazas",
    "721": "https://www.geradovana.lt/spa-ir-masazai/svediskas-masazas",
    "722": "https://www.geradovana.lt/spa-ir-masazai/anticeliulitinis-masazas",
    "724": "https://www.geradovana.lt/spa-ir-masazai/koju-masazas",
    "725": "https://www.geradovana.lt/spa-ir-masazai/masazai",
    "726": "https://www.geradovana.lt/spa-ir-masazai/kobido",
    "727": "https://www.geradovana.lt/spa-ir-masazai/rytietiski-masazai",
    "728": "https://www.geradovana.lt/spa-ir-masazai/ajurvedinis-masazas",
    "729": "https://www.geradovana.lt/spa-ir-masazai/taskinis-masazas",
    "730": "https://www.geradovana.lt/spa-ir-masazai/masazai-dviems",
    "731": "https://www.geradovana.lt/spa-ir-masazai/spa",
    "732": "https://www.geradovana.lt/spa-ir-masazai/pirtis",
    "733": "https://www.geradovana.lt/spa-ir-masazai/pluduriavimas",
    "734": "https://www.geradovana.lt/spa-ir-masazai/dienos-spa",
    "735": "https://www.geradovana.lt/spa-ir-masazai/spa-centras",
    "736": "https://www.geradovana.lt/spa-ir-masazai/plauku-spa",
    "737": "https://www.geradovana.lt/spa-ir-masazai/spa-viesbutis",
}
