"""Category catalog for LV - Generated from tree file."""

# Category ID to Name mapping
CATEGORY_NAME_MAP: dict[str, str] = {
    "174": "Vieta",
    "175": "Rīga",
    "177": "Jūrmala",
    "179": "Ādaži",
    "181": "Ogre",
    "183": "Jelgava",
    "185": "Bauska",
    "187": "Liepāja",
    "189": "Valmiera",
    "191": "Sigulda",
    "193": "Daugavpils",
    "195": "Rēzekne",
    "196": "Rēzeknes nov.",
    "197": "Citās pilsētās",
    "198": "Visā Latvijā",
    "199": "Lietuva",
    "200": "Igaunija",
    "202": "Lidojumi un lēcieni",
    "203": "Lidojumi ar gaisa balonu",
    "204": "Lēciens ar izpletni",
    "205": "Lidojumi ar paraplānu",
    "206": "Lidojums ar lidmašīnu",
    "207": "Lidojumi ar deltaplānu",
    "208": "Aerodium vēja tunelis",
    "209": "Ūdens piedzīvojumi",
    "210": "Ūdens atrakciju parki",
    "211": "Izbrauciens ar jahtu",
    "212": "Daivings",
    "213": "Laivu noma",
    "214": "Kaitbords",
    "215": "Veikbords",
    "216": "Vindsērfings",
    "217": "Citas ūdens izklaides",
    "218": "Aktīvā atpūta",
    "219": "Šaušana",
    "220": "Izjādes ar zirgiem",
    "221": "Braucieni",
    "222": "Deju nodarbības",
    "223": "Piedzīvojumu parki",
    "224": "Boulings",
    "225": "Skaistums",
    "226": "Sejas procedūras",
    "227": "Procedūras matiem",
    "228": "Procedūras ķermenim",
    "229": "Procedūru kompleksi",
    "230": "Manikīrs",
    "231": "Procedūras vīriešiem",
    "232": "Vizāžas un stila kursi",
    "233": "Atpūta Latvijā",
    "234": "Rīga",
    "235": "Kurzeme",
    "236": "Zemgale",
    "237": "Vidzeme",
    "238": "Latgale",
    "239": "Lietuva",
    "240": "1 nakts",
    "241": "2 naktis",
    "242": "1 personai",
    "243": "Atpūta diviem",
    "244": "3 personām",
    "245": "Ģimenes atpūta",
    "246": "SPA un masāžas",
    "247": "SPA un masāža diviem",
    "248": "Pilna ķermeņa masāža",
    "249": "Muguras masāža",
    "251": "SPA procedūras",
    "252": "Masāžas vīriešiem",
    "253": "Gardēžiem",
    "254": "Vakariņas",
    "255": "Degustācijas",
    "256": "Kursi",
    "257": "Jautras dāvanas",
    "258": "Fotosesija",
    "259": "Ekskursijas",
    "260": "Kvesti",
    "261": "Kino",
    "263": "Kursi un Meistarklases",
    "264": "Veselībai un labsajūtai",
    "265": "SPA centri",
    "266": "Baseini",
    "267": "Kriosauna",
    "268": "Solārijs",
    "269": "Aktīvā atpūta ziemā",
    "270": "Slēpošana",
    "271": "Braukšana ar snovbordu",
    "272": "Izbraucieni ar sniega motociklu",
    "273": "Slidošana",
    "274": "Brauciens pajūgā",
    "330": "Dāvanu komplekti",
    "331": "Veikalu dāvanu kartes",
    "332": "Preses abonementi",
    "353": "Vidzeme",
    "354": "Kurzeme",
    "355": "Zemgale",
    "356": "Latgale",
    "362": "Vēlās brokastis",
    "364": "Ventspils",
    "365": "Lamborghini",
    "366": "Biķernieku trase",
    "367": "Cēsis",
    "369": "Līgatne",
    "374": "Palanga",
    "375": "Igaunija",
    "376": "Aizkraukle",
    "377": "Kartingi",
    "378": "Druskininki",
    "379": "Superauto",
    "381": "Jēkabpils",
    "383": "Madona",
    "385": "Birštona",
    "390": "Tallina",
    "391": "Pērnava",
    "393": "Tukums",
    "404": "T/C dāvanu kartes",
    "408": "Smiltene",
    "411": "Polija",
    "412": "Austrija",
    "413": "Ungārija",
    "414": "Polija",
    "419": "Izklaides no mājām",
    "420": "Izklaides brīvā dabā",
    "421": "Grāmatas un žurnāli",
    "422": "Ēdieni līdzņemšanai",
    "423": "Iepirkšanās tiešsaitē",
    "424": "Tiešsaites semināri un apmācības",
    "426": "Atpūta ārzemēs",
    "428": "Pilsētas kartes",
    "429": "Bobsleja trase",
    "431": "Lidojums ar helikopteru",
    "432": "Jūrmala",
    "433": "Sigulda",
    "434": "SPA atpūta",
    "435": "Atpūta pie jūras",
    "436": "Atpūta pie ezera",
    "437": "Atpūta laukos",
    "438": "Atpūtas namiņi",
    "439": "Atpūtas komplekss",
    "440": "Dienas SPA",
    "441": "Ājurvēdas masāža",
    "442": "Ārstnieciskā masāža",
    "443": "Galvas masāža",
    "444": "Grūtnieču masāža",
    "445": "Karsto akmeņu masāža",
    "446": "Limfodrenāžas masāža",
    "447": "LPG masāža",
    "448": "Pēdu masāža",
    "449": "Relaksējoša masāža",
    "450": "Sejas masāža",
    "451": "Šokolādes masāža",
    "452": "Sporta masāža",
    "453": "Taizemes masāža",
    "454": "Makšķerēšana",
    "456": "Kajaku noma",
    "457": "Kruīzs",
    "458": "SUP noma",
    "459": "Brauciens ar kuģīti",
    "460": "Ūdens motociklu noma",
    "461": "Floutings",
    "462": "Sāls istaba",
    "463": "Pirts",
    "464": "Hammam",
    "465": "DNS tests",
    "466": "Šautuve",
    "467": "Lāzertags",
    "468": "Loka šaušana",
    "469": "Sports",
    "470": "Boulderings",
    "471": "VR",
    "472": "Spēles",
    "473": "Brauciens ar Ferrari",
    "474": "Brauciens ar Lamborghini",
    "475": "Drifts",
    "476": "Brauciens ar kvadraciklu",
    "477": "Brauciens ar motociklu",
    "478": "Brauciens ar bagiju",
    "479": "Braukšanas apmācība",
    "480": "Individuāla fotosesija",
    "481": "Pāru fotosesija",
    "482": "Grūtnieču fotosesija",
    "483": "Ziemassvētku fotosesija",
    "484": "Karikatūras",
    "485": "Floristikas kursi",
    "486": "Ziepju izgatavošana",
    "488": "Foto kursi",
    "489": "Gleznošanas kursi",
    "490": "Online kursi",
    "491": "Rotaslietu izgatavošana",
    "492": "Smaržu darbnīca",
    "493": "Mūzikas nodarbības",
    "495": "Zoo",
    "496": "Teātri",
    "497": "Interesantas dāvanas",
    "498": "Pedikīrs",
    "499": "Vaksācija",
    "500": "Skropstas un Uzacis",
    "501": "Barbershop",
    "502": "Zobārstniecība",
    "503": "Zobu balināšana",
    "504": "Zobu higiēna",
    "505": "Tetovēšanas salons",
    "506": "Deguna un Nabas pīrsings",
    "507": "Romantiskas vakariņas",
    "508": "Restorāni un kafejnīcas",
    "509": "Vīna degustācija",
    "510": "Alus degustācija",
    "511": "Deserts",
    "515": "Ēdienu piegāde",
    "516": "Atpūta Tallinā",
    "517": "Atpūta Tartu",
    "518": "SPA Pērnavā",
    "519": "Atpūta Sāremā",
    "520": "Sanatorijas Lietuvā",
    "521": "Viļņa",
    "522": "Šauļi",
    "523": "Traķi",
    "525": "Romantiska atpūta diviem",
    "529": "Pirts rituāls",
    "532": "Atpūta pie dabas",
    "536": "Vakariņas tumsā",
    "537": "Ģimenes fotosesija",
    "538": "Airsoft",
    "539": "SPA Igaunijā",
    "540": "SPA Lietuvā",
    "542": "Peintbols",
    "543": "Lēciens ar gumiju",
    "548": "Tartu",
    "554": "Dāvanu kartes",
    "555": "SPA dāvanu kartes",
    "556": "Restorānu dāvanu kartes",
    "557": "Piedzīvojumu dāvanu kartes",
    "558": "Veikalu dāvanu kartes",
    "559": "Viesnīcu Dāvanu Kartes",
    "560": "Masāžas",
    "561": "SPA",
    "563": "SPA Viesnīcas Latvijā",
    "564": "SPA muižas",
    "565": "Vakuuma masāža",
    "566": "Taktīlā masāža",
    "568": "Zemūdens masāža",
    "574": "Atpūtas vietas",
    "575": "Naktsmītnes",
    "576": "Naktsmītnes pie jūras",
    "577": "Naktsmītnes pie ezera",
    "578": "Skaistas naktsmītnes Latvijā",
    "579": "Romantiskas naktsmītnes",
    "580": "Sanatorija",
    "581": "Namiņi pie ezera",
    "582": "Namiņi pie jūras",
    "583": "SPA atpūta Rīgā",
    "584": "SPA atpūta Jūrmalā",
    "585": "SPA atpūta Latvijā",
    "586": "Spa atpūta Lietuvā",
    "587": "Spa atpūta Igaunijā",
    "588": "Atpūta ar bērniem",
    "589": "Atpūta ārpus Rīgas",
    "592": "Kanoe noma",
    "593": "Motorlaivas",
    "594": "Airu laivas",
    "595": "Makšķerēšana ar naktsmītni",
    "596": "Jahtu noma",
    "597": "Motorjahtas",
    "598": "Plosti",
    "599": "Ūdens formulas",
    "600": "Efoil",
    "612": "Meistarklases",
    "613": "Bērniem meistarklases",
    "614": "Meistarklases sievietēm",
    "615": "Meistarklases vīriešiem",
    "617": "Auto kursi",
    "618": "Kursi pieaugušajiem",
    "619": "Keramikas meistarklase",
    "620": "Gatavošanas meistarklases",
    "621": "Makarūnu meistarklase",
    "622": "Kūku cepšanas meistarklase",
    "623": "Picu meistarklase",
    "624": "Zīmēšanas kursi",
    "631": "Žurnāli vīriešiem",
    "632": "Bērnu žurnāli",
    "633": "Jauniešu žurnāli",
    "634": "Krustvārdu mīklas",
    "635": "Pirtis Rīgā",
    "636": "Pirtis Pierīgā",
    "637": "Koka pirtis",
    "638": "Mazas pirtis",
    "639": "Pirts mājas",
    "640": "Pirtis ar kublu",
    "641": "Pirts rituāls diviem",
    "642": "Pirts rituāls ar pirtnieku",
    "643": "Pirts SPA",
    "644": "Baseini Rīgā",
    "645": "Baseini Jūrmalā",
    "650": "Golfs",
    "651": "Klasiskais golfs",
    "652": "Disku golfs",
    "653": "Mini golf",
    "654": "Futbolgolfs",
    "655": "Skvošs",
    "656": "Izklaides",
    "658": "Sporta klubi",
    "659": "Joga",
    "660": "Orientēšanās",
    "661": "Pārgājieni",
    "662": "Kērlings",
    "663": "Kikbokss",
    "665": "Restorāni",
    "666": "Itāļu restorāns",
    "667": "Armēņu restorāns",
    "668": "Kafejnīcas",
    "669": "Kafejnīcas Vecrīgā",
    "670": "Kafejnīca Rīgas centrā",
    "671": "Omulīgas kafejnīcas",
    "672": "Labākās kafejnīcas Rīgā",
    "673": "Brokastis",
    "675": "Vakariņas restorānā",
    "676": "Ģimenei draudzīgas vakariņas",
    "677": "Kur paēst vakariņas Rīgā",
    "679": "Šmakovkas degustācija",
    "680": "Picērijas",
    "681": "Labākie restorāni",
    "682": "Padel teniss",
    "684": "Lidojums ar gaisa balonu Jelgavā",
    "685": "Lidojums virs Rīgas",
    "686": "Lidojums virs Siguldas",
    "687": "Lidojums ar motodeltaplānu",
    "709": "Visā pasaulē",
    "712": "Frizētava",
    "713": "Ausu caurduršana",
    "714": "Ausu caurduršana Rīgā",
    "715": "Ausu caurduršana Bērniem",
    "716": "Japāņu manikīrs",
    "717": "Franču manikīrs",
    "718": "Klasiskais manikīrs",
    "719": "Ārstnieciskais pedikīrs",
    "720": "Pedikīrs Rīgā",
    "721": "Vaksācija Rīgā",
    "722": "Bikini vaksācija",
    "723": "Vaksācija vīriešiem",
    "724": "Muguras vaksācija vīriešiem",
    "725": "Sejas vaksācija",
    "726": "Skropstu pieaudzēšana",
    "727": "Skropstu laminēšana",
    "728": "Uzacu laminēšana",
    "729": "Permanentās uzacis",
    "730": "Uzacu korekcija",
    "731": "Uzacu krāsošana",
    "732": "Terapijas",
    "733": "Mezoterapija",
    "734": "Krioterapija",
    "735": "Ultraskaņas terapija",
    "736": "Endosfēras terapija",
    "737": "Lāzerepilācija",
    "738": "Anti-ageing",
    "739": "Liftings",
    "740": "Dermapen",
    "741": "Kavitācija",
    "744": "Fizioterapija",
    "756": "Masāžu kursi",
    "757": "Glempings",
    "759": "Klaipēda",
    "760": "SPA Palangā",
    "765": "SPA Druskininki",
    "766": "Smaržu meistarklase",
    "767": "Aromaterapija",
    "768": "Sveču liešanas meistarklase",
    "770": "Āzijas virtuve",
    "771": "Biljards",
    "780": "Pilates",
    "781": "Pils",
    "782": "Rotaslietas",
}

# Category ID to URL mapping
CATEGORY_URL_MAP: dict[str, str] = {
    "174": "https://www.lieliskadavana.lv/vieta",
    "175": "https://www.lieliskadavana.lv/davanas-riga",
    "177": "https://www.lieliskadavana.lv/davanas-jurmala",
    "179": "https://www.lieliskadavana.lv/davanas-adazos",
    "181": "https://www.lieliskadavana.lv/davanas-ogre",
    "183": "https://www.lieliskadavana.lv/davanas-jelgava",
    "185": "https://www.lieliskadavana.lv/davanas-bauska",
    "187": "https://www.lieliskadavana.lv/davanas-liepaja",
    "189": "https://www.lieliskadavana.lv/davanas-valmiera",
    "191": "https://www.lieliskadavana.lv/davanas-sigulda",
    "193": "https://www.lieliskadavana.lv/davanas-daugavpili",
    "195": "https://www.lieliskadavana.lv/davanas-rezekne",
    "196": "https://www.lieliskadavana.lv/rezeknes-nov",
    "197": "https://www.lieliskadavana.lv/davanas-citas-pilsetas",
    "198": "https://www.lieliskadavana.lv/davanas-visa-latvija",
    "199": "https://www.lieliskadavana.lv/davanas-lietuva",
    "200": "https://www.lieliskadavana.lv/davanas-igaunija",
    "202": "https://www.lieliskadavana.lv/lidojumi-un-lecieni",
    "203": "https://www.lieliskadavana.lv/lidojumi-un-lecieni/lidojumi-ar-gaisa-balonu",
    "204": "https://www.lieliskadavana.lv/lidojumi-un-lecieni/lecieni",
    "205": "https://www.lieliskadavana.lv/lidojumi-un-lecieni/lidojumi-ar-paraplanu",
    "206": "https://www.lieliskadavana.lv/lidojumi-un-lecieni/lidojums-ar-lidmasinu",
    "207": "https://www.lieliskadavana.lv/lidojumi-un-lecieni/lidojumi-ar-deltaplanu",
    "208": "https://www.lieliskadavana.lv/aerodium-veja-tunelis",
    "209": "https://www.lieliskadavana.lv/udens-piedzivojumi",
    "210": "https://www.lieliskadavana.lv/udens-piedzivojumi/udens-atrakciju-parki",
    "211": "https://www.lieliskadavana.lv/udens-piedzivojumi/brauciens-ar-kugi-vai-jahtu",
    "212": "https://www.lieliskadavana.lv/udens-piedzivojumi/nirsana",
    "213": "https://www.lieliskadavana.lv/udens-piedzivojumi/izbraucieni-ar-laivam",
    "214": "https://www.lieliskadavana.lv/udens-piedzivojumi/kaitbords",
    "215": "https://www.lieliskadavana.lv/udens-piedzivojumi/veikbords",
    "216": "https://www.lieliskadavana.lv/udens-piedzivojumi/vindserfings",
    "217": "https://www.lieliskadavana.lv/udens-piedzivojumi/citas-udens-izklaides",
    "218": "https://www.lieliskadavana.lv/aktiva-atputa",
    "219": "https://www.lieliskadavana.lv/aktiva-atputa/sausana",
    "220": "https://www.lieliskadavana.lv/aktiva-atputa/izjades",
    "221": "https://www.lieliskadavana.lv/izklaide-pie-stures",
    "222": "https://www.lieliskadavana.lv/kursi-un-meistarklases/deju-nodarbibas",
    "223": "https://www.lieliskadavana.lv/aktiva-atputa/piedzivojumu-parki",
    "224": "https://www.lieliskadavana.lv/aktiva-atputa/boulings",
    "225": "https://www.lieliskadavana.lv/skaistumkopsana",
    "226": "https://www.lieliskadavana.lv/skaistumkopsana/sejas-proceduras",
    "227": "https://www.lieliskadavana.lv/skaistumkopsana/proceduras-matiem",
    "228": "https://www.lieliskadavana.lv/skaistumkopsana/proceduras-kermenim",
    "229": "https://www.lieliskadavana.lv/skaistumkopsana/proceduru-kompleksi",
    "230": "https://www.lieliskadavana.lv/skaistumkopsana/manikirs",
    "231": "https://www.lieliskadavana.lv/skaistumkopsana/proceduras-viriesiem",
    "232": "https://www.lieliskadavana.lv/kursi-un-meistarklases/vizazas-un-stila-kursi",
    "233": "https://www.lieliskadavana.lv/naksnosana",
    "234": "https://www.lieliskadavana.lv/naksnosana/naksnosana-riga",
    "235": "https://www.lieliskadavana.lv/naksnosana/naksnosana-kurzeme",
    "236": "https://www.lieliskadavana.lv/naksnosana/naksnosana-zemgale",
    "237": "https://www.lieliskadavana.lv/naksnosana/naksnosana-vidzeme",
    "238": "https://www.lieliskadavana.lv/naksnosana/naksnosana-latgale",
    "239": "https://www.lieliskadavana.lv/atputa-arzemes/naksnosana-lietuva",
    "240": "https://www.lieliskadavana.lv/naksnosana/1-nakts",
    "241": "https://www.lieliskadavana.lv/naksnosana/2-naktis",
    "242": "https://www.lieliskadavana.lv/naksnosana/1-personai",
    "243": "https://www.lieliskadavana.lv/naksnosana/2-personam",
    "244": "https://www.lieliskadavana.lv/naksnosana/3-personam",
    "245": "https://www.lieliskadavana.lv/naksnosana/vairak-ka-3-personam",
    "246": "https://www.lieliskadavana.lv/spa-un-masazas",
    "247": "https://www.lieliskadavana.lv/spa-un-masazas/spa-un-masaza-diviem",
    "248": "https://www.lieliskadavana.lv/spa-un-masazas/masazas/pilna-kermena-masaza",
    "249": "https://www.lieliskadavana.lv/spa-un-masazas/muguras-masaza",
    "251": "https://www.lieliskadavana.lv/spa-un-masazas/spa/spa-proceduras",
    "252": "https://www.lieliskadavana.lv/spa-un-masazas/masazas-viriesiem",
    "253": "https://www.lieliskadavana.lv/davanas-gardeziem",
    "254": "https://www.lieliskadavana.lv/davanas-gardeziem/vakarinas",
    "255": "https://www.lieliskadavana.lv/davanas-gardeziem/degustacijas",
    "256": "https://www.lieliskadavana.lv/kursi-un-meistarklases/kursi",
    "257": "https://www.lieliskadavana.lv/jautras-davanas",
    "258": "https://www.lieliskadavana.lv/jautras-davanas/fotosesija",
    "259": "https://www.lieliskadavana.lv/jautras-davanas/ekskursijas",
    "260": "https://www.lieliskadavana.lv/jautras-davanas/kvesti",
    "261": "https://www.lieliskadavana.lv/jautras-davanas/kino",
    "263": "https://www.lieliskadavana.lv/kursi-un-meistarklases",
    "264": "https://www.lieliskadavana.lv/veselibai-un-labsajutai",
    "265": "https://www.lieliskadavana.lv/veselibai-un-labsajutai/spa-centri",
    "266": "https://www.lieliskadavana.lv/veselibai-un-labsajutai/baseini",
    "267": "https://www.lieliskadavana.lv/veselibai-un-labsajutai/kriosauna",
    "268": "https://www.lieliskadavana.lv/veselibai-un-labsajutai/solarijs",
    "269": "https://www.lieliskadavana.lv/aktiva-atputa-ziema",
    "270": "https://www.lieliskadavana.lv/aktiva-atputa-ziema/sleposana",
    "271": "https://www.lieliskadavana.lv/aktiva-atputa-ziema/brauksana-ar-snovbordu",
    "272": "https://www.lieliskadavana.lv/aktiva-atputa-ziema/izbraucieni-ar-sniega-motociklu",
    "273": "https://www.lieliskadavana.lv/aktiva-atputa-ziema/slidosana",
    "274": "https://www.lieliskadavana.lv/aktiva-atputa-ziema/brauciens-pajuga",
    "330": "https://www.lieliskadavana.lv/davanu-komplekti",
    "331": "https://www.lieliskadavana.lv/davanu-kartes-precei",
    "332": "https://www.lieliskadavana.lv/jautras-davanas/preses-abonementi",
    "353": "https://www.lieliskadavana.lv/davanas-vidzeme",
    "354": "https://www.lieliskadavana.lv/davanas-kurzeme",
    "355": "https://www.lieliskadavana.lv/davanas-zemgale",
    "356": "https://www.lieliskadavana.lv/davanas-latgale",
    "362": "https://www.lieliskadavana.lv/davanas-gardeziem/velas-brokastis",
    "364": "https://www.lieliskadavana.lv/ventspils",
    "365": "https://www.lieliskadavana.lv/lamborghini",
    "366": "https://www.lieliskadavana.lv/bikernieku-trase",
    "367": "https://www.lieliskadavana.lv/cesis",
    "369": "https://www.lieliskadavana.lv/ligatne",
    "374": "https://www.lieliskadavana.lv/atputa-arzemes/naksnosana-lietuva/palanga",
    "375": "https://www.lieliskadavana.lv/atputa-arzemes/igaunija",
    "376": "https://www.lieliskadavana.lv/aizkraukle",
    "377": "https://www.lieliskadavana.lv/izklaide-pie-stures/kartingi",
    "378": "https://www.lieliskadavana.lv/atputa-arzemes/naksnosana-lietuva/druskininki",
    "379": "https://www.lieliskadavana.lv/izklaide-pie-stures/superauto",
    "381": "https://www.lieliskadavana.lv/jekabpils",
    "383": "https://www.lieliskadavana.lv/madona",
    "385": "https://www.lieliskadavana.lv/atputa-arzemes/naksnosana-lietuva/birstonas",
    "390": "https://www.lieliskadavana.lv/tallina",
    "391": "https://www.lieliskadavana.lv/pernava",
    "393": "https://www.lieliskadavana.lv/davanas-tukuma",
    "404": "https://www.lieliskadavana.lv/tirdzniecibas-centra-davanu-karte",
    "408": "https://www.lieliskadavana.lv/smiltene",
    "411": "https://www.lieliskadavana.lv/polija",
    "412": "https://www.lieliskadavana.lv/austrija",
    "413": "https://www.lieliskadavana.lv/ungarija",
    "414": "https://www.lieliskadavana.lv/atputa-arzemes/naksnosana-polija",
    "419": "https://www.lieliskadavana.lv/izklaide-no-majam",
    "420": "https://www.lieliskadavana.lv/izklaides-briva-daba",
    "421": "https://www.lieliskadavana.lv/izklaide-no-majam/gramatas-un-zurnali",
    "422": "https://www.lieliskadavana.lv/izklaide-no-majam/edieni-lidznemsanai",
    "423": "https://www.lieliskadavana.lv/izklaide-no-majam/iepirksanas-tiessaite",
    "424": "https://www.lieliskadavana.lv/izklaide-no-majam/tiessaites-seminari-un-apmacibas",
    "426": "https://www.lieliskadavana.lv/atputa-arzemes",
    "428": "https://www.lieliskadavana.lv/pilsetas-kartes",
    "429": "https://www.lieliskadavana.lv/aktiva-atputa-ziema/bobsleja-trase",
    "431": "https://www.lieliskadavana.lv/lidojumi-un-lecieni/lidojums-ar-helikopteru",
    "432": "https://www.lieliskadavana.lv/naksnosana/jurmala",
    "433": "https://www.lieliskadavana.lv/naksnosana/sigulda",
    "434": "https://www.lieliskadavana.lv/naksnosana/spa-atputa",
    "435": "https://www.lieliskadavana.lv/naksnosana/atputa-pie-juras",
    "436": "https://www.lieliskadavana.lv/naksnosana/atputas-vietas/atputa-pie-ezera",
    "437": "https://www.lieliskadavana.lv/naksnosana/atputas-vietas/atputa-laukos",
    "438": "https://www.lieliskadavana.lv/naksnosana/atputas-namins",
    "439": "https://www.lieliskadavana.lv/naksnosana/atputas-komplekss",
    "440": "https://www.lieliskadavana.lv/spa-un-masazas/spa/dienas-spa",
    "441": "https://www.lieliskadavana.lv/spa-un-masazas/masazas/ajurvedas-masaza",
    "442": "https://www.lieliskadavana.lv/spa-un-masazas/arstnieciska-masaza",
    "443": "https://www.lieliskadavana.lv/spa-un-masazas/masazas/galvas-masaza",
    "444": "https://www.lieliskadavana.lv/spa-un-masazas/masazas/grutniecu-masaza",
    "445": "https://www.lieliskadavana.lv/spa-un-masazas/masazas/karsto-akmenu-masaza",
    "446": "https://www.lieliskadavana.lv/spa-un-masazas/limfodrenazas-masaza",
    "447": "https://www.lieliskadavana.lv/spa-un-masazas/lpg-masaza",
    "448": "https://www.lieliskadavana.lv/spa-un-masazas/masazas/pedu-masaza",
    "449": "https://www.lieliskadavana.lv/spa-un-masazas/relaksejosa-masaza",
    "450": "https://www.lieliskadavana.lv/spa-un-masazas/sejas-masaza",
    "451": "https://www.lieliskadavana.lv/spa-un-masazas/masazas/sokolades-masaza",
    "452": "https://www.lieliskadavana.lv/spa-un-masazas/masazas/sporta-masaza",
    "453": "https://www.lieliskadavana.lv/spa-un-masazas/taizemes-masaza",
    "454": "https://www.lieliskadavana.lv/udens-piedzivojumi/makskeresana",
    "456": "https://www.lieliskadavana.lv/udens-piedzivojumi/izbraucieni-ar-laivam/kajaku-noma",
    "457": "https://www.lieliskadavana.lv/udens-piedzivojumi/kruizs",
    "458": "https://www.lieliskadavana.lv/udens-piedzivojumi/sup-noma",
    "459": "https://www.lieliskadavana.lv/udens-piedzivojumi/brauciens-ar-kugiti",
    "460": "https://www.lieliskadavana.lv/udens-piedzivojumi/udens-motociklu-noma",
    "461": "https://www.lieliskadavana.lv/veselibai-un-labsajutai/floutings",
    "462": "https://www.lieliskadavana.lv/veselibai-un-labsajutai/sals-istaba",
    "463": "https://www.lieliskadavana.lv/veselibai-un-labsajutai/pirts",
    "464": "https://www.lieliskadavana.lv/veselibai-un-labsajutai/hammam",
    "465": "https://www.lieliskadavana.lv/veselibai-un-labsajutai/dns-tests",
    "466": "https://www.lieliskadavana.lv/aktiva-atputa/sausana/sautuve",
    "467": "https://www.lieliskadavana.lv/aktiva-atputa/sausana/lazertags",
    "468": "https://www.lieliskadavana.lv/aktiva-atputa/sausana/loka-sausana",
    "469": "https://www.lieliskadavana.lv/aktiva-atputa/sports",
    "470": "https://www.lieliskadavana.lv/aktiva-atputa/boulderings",
    "471": "https://www.lieliskadavana.lv/aktiva-atputa/virtuala-realitate",
    "472": "https://www.lieliskadavana.lv/aktiva-atputa/speles",
    "473": "https://www.lieliskadavana.lv/izklaide-pie-stures/superauto/brauciens-ar-ferrari",
    "474": "https://www.lieliskadavana.lv/izklaide-pie-stures/superauto/brauciens-ar-lamborghini",
    "475": "https://www.lieliskadavana.lv/izklaide-pie-stures/drifts",
    "476": "https://www.lieliskadavana.lv/izklaide-pie-stures/brauciens-ar-kvadraciklu",
    "477": "https://www.lieliskadavana.lv/izklaide-pie-stures/brauciens-ar-motociklu",
    "478": "https://www.lieliskadavana.lv/izklaide-pie-stures/brauciens-ar-bagiju",
    "479": "https://www.lieliskadavana.lv/izklaide-pie-stures/brauksanas-apmaciba",
    "480": "https://www.lieliskadavana.lv/jautras-davanas/fotosesija/individuala-fotosesija",
    "481": "https://www.lieliskadavana.lv/jautras-davanas/fotosesija/paru-fotosesija",
    "482": "https://www.lieliskadavana.lv/jautras-davanas/fotosesija/grutniecu-fotosesija",
    "483": "https://www.lieliskadavana.lv/jautras-davanas/fotosesija/ziemassvetku-fotosesija",
    "484": "https://www.lieliskadavana.lv/jautras-davanas/karikaturas",
    "485": "https://www.lieliskadavana.lv/kursi-un-meistarklases/floristikas-kursi",
    "486": "https://www.lieliskadavana.lv/kursi-un-meistarklases/ziepju-izgatavosana",
    "488": "https://www.lieliskadavana.lv/kursi-un-meistarklases/foto-kursi",
    "489": "https://www.lieliskadavana.lv/kursi-un-meistarklases/gleznosanas-kursi",
    "490": "https://www.lieliskadavana.lv/kursi-un-meistarklases/online-kursi",
    "491": "https://www.lieliskadavana.lv/kursi-un-meistarklases/rotaslietu-izgatavosana",
    "492": "https://www.lieliskadavana.lv/kursi-un-meistarklases/smarzu-darbnica",
    "493": "https://www.lieliskadavana.lv/kursi-un-meistarklases/muzikas-nodarbibas",
    "495": "https://www.lieliskadavana.lv/jautras-davanas/zoo",
    "496": "https://www.lieliskadavana.lv/jautras-davanas/teatri",
    "497": "https://www.lieliskadavana.lv/jautras-davanas/interesantas-davanas",
    "498": "https://www.lieliskadavana.lv/skaistumkopsana/pedikirs",
    "499": "https://www.lieliskadavana.lv/skaistumkopsana/vaksacija",
    "500": "https://www.lieliskadavana.lv/skaistumkopsana/skropstasuzacis",
    "501": "https://www.lieliskadavana.lv/skaistumkopsana/barbershop",
    "502": "https://www.lieliskadavana.lv/veselibai-un-labsajutai/zobarstnieciba",
    "503": "https://www.lieliskadavana.lv/veselibai-un-labsajutai/zobarstnieciba/zobu-balinasana",
    "504": "https://www.lieliskadavana.lv/veselibai-un-labsajutai/zobarstnieciba/zobu-higiena",
    "505": "https://www.lieliskadavana.lv/skaistumkopsana/tetovesana",
    "506": "https://www.lieliskadavana.lv/skaistumkopsana/deguna-nabas-pirsings",
    "507": "https://www.lieliskadavana.lv/davanas-gardeziem/vakarinas/romantiskas-vakarinas",
    "508": "https://www.lieliskadavana.lv/davanas-gardeziem/restorani-un-kafejnicas",
    "509": "https://www.lieliskadavana.lv/davanas-gardeziem/degustacijas/vina-degustacija",
    "510": "https://www.lieliskadavana.lv/davanas-gardeziem/degustacijas/alus-degustacija",
    "511": "https://www.lieliskadavana.lv/davanas-gardeziem/deserts",
    "515": "https://www.lieliskadavana.lv/davanas-gardeziem/edienu-piegade",
    "516": "https://www.lieliskadavana.lv/atputa-arzemes/igaunija/atputa-tallina",
    "517": "https://www.lieliskadavana.lv/atputa-arzemes/igaunija/atputa-tartu",
    "518": "https://www.lieliskadavana.lv/atputa-arzemes/igaunija/spa-pernava",
    "519": "https://www.lieliskadavana.lv/atputa-arzemes/igaunija/atputa-sarema",
    "520": "https://www.lieliskadavana.lv/atputa-arzemes/naksnosana-lietuva/sanatorijas-lietuva",
    "521": "https://www.lieliskadavana.lv/atputa-arzemes/naksnosana-lietuva/atputa-vilna",
    "522": "https://www.lieliskadavana.lv/atputa-arzemes/naksnosana-lietuva/atputa-saulos",
    "523": "https://www.lieliskadavana.lv/atputa-arzemes/naksnosana-lietuva/atputa-trakos",
    "525": "https://www.lieliskadavana.lv/naksnosana/romantiska-atputa-diviem",
    "529": "https://www.lieliskadavana.lv/veselibai-un-labsajutai/pirts-rituals",
    "532": "https://www.lieliskadavana.lv/naksnosana/atputas-vietas/atputa-pie-dabas",
    "536": "https://www.lieliskadavana.lv/davanas-gardeziem/vakarinas/tumsa",
    "537": "https://www.lieliskadavana.lv/jautras-davanas/fotosesija/gimenes-fotosesija",
    "538": "https://www.lieliskadavana.lv/aktiva-atputa/sausana/airsoft",
    "539": "https://www.lieliskadavana.lv/atputa-arzemes/igaunija/spa-igaunija",
    "540": "https://www.lieliskadavana.lv/atputa-arzemes/naksnosana-lietuva/spa-lietuva",
    "542": "https://www.lieliskadavana.lv/aktiva-atputa/peintbols",
    "543": "https://www.lieliskadavana.lv/lidojumi-un-lecieni/leciens-ar-gumiju",
    "548": "https://www.lieliskadavana.lv/tartu",
    "554": "https://www.lieliskadavana.lv/davanu-kartes",
    "555": "https://www.lieliskadavana.lv/spa-un-masazas/spa/spa-davanu-kartes",
    "556": "https://www.lieliskadavana.lv/restoranu-davanu-kartes",
    "557": "https://www.lieliskadavana.lv/piedzivojumu-davanu-kartes",
    "558": "https://www.lieliskadavana.lv/veikalu-davanu-kartes",
    "559": "https://www.lieliskadavana.lv/viesnicu-davanu-kartes",
    "560": "https://www.lieliskadavana.lv/spa-un-masazas/masazas",
    "561": "https://www.lieliskadavana.lv/spa-un-masazas/spa",
    "563": "https://www.lieliskadavana.lv/spa-un-masazas/spa-viesnicas-latvija",
    "564": "https://www.lieliskadavana.lv/spa-un-masazas/spa-viesnicas-latvija/spa-muizas",
    "565": "https://www.lieliskadavana.lv/spa-un-masazas/masazas/vakuuma-masaza",
    "566": "https://www.lieliskadavana.lv/spa-un-masazas/masazas/taktila-masaza",
    "568": "https://www.lieliskadavana.lv/spa-un-masazas/zemudens-masaza",
    "574": "https://www.lieliskadavana.lv/naksnosana/atputas-vietas",
    "575": "https://www.lieliskadavana.lv/naksnosana/naktsmitnes",
    "576": "https://www.lieliskadavana.lv/naksnosana/naktsmitnes/naktsmitnes-pie-juras",
    "577": "https://www.lieliskadavana.lv/naksnosana/naktsmitnes/naktsmitnes-pie-ezera",
    "578": "https://www.lieliskadavana.lv/naksnosana/naktsmitnes/skaistas-naktsmitnes-latvija",
    "579": "https://www.lieliskadavana.lv/naksnosana/naktsmitnes/romantiskas-naktsmitnes",
    "580": "https://www.lieliskadavana.lv/naksnosana/sanatorija",
    "581": "https://www.lieliskadavana.lv/naksnosana/atputas-namins/namini-pie-ezera",
    "582": "https://www.lieliskadavana.lv/naksnosana/atputas-namins/namini-pie-juras",
    "583": "https://www.lieliskadavana.lv/naksnosana/spa-atputa/spa-atputa-riga",
    "584": "https://www.lieliskadavana.lv/naksnosana/spa-atputa/spa-atputa-jurmala",
    "585": "https://www.lieliskadavana.lv/naksnosana/spa-atputa/spa-atputa-latvija",
    "586": "https://www.lieliskadavana.lv/naksnosana/spa-atputa/spa-atputa-lietuva",
    "587": "https://www.lieliskadavana.lv/naksnosana/spa-atputa/spa-atputa-igaunija",
    "588": "https://www.lieliskadavana.lv/naksnosana/atputa-ar-berniem",
    "589": "https://www.lieliskadavana.lv/naksnosana/atputa-arpus-rigas",
    "592": "https://www.lieliskadavana.lv/udens-piedzivojumi/izbraucieni-ar-laivam/kanoe-noma",
    "593": "https://www.lieliskadavana.lv/udens-piedzivojumi/izbraucieni-ar-laivam/motorlaivas",
    "594": "https://www.lieliskadavana.lv/udens-piedzivojumi/izbraucieni-ar-laivam/airu-laivas",
    "595": "https://www.lieliskadavana.lv/udens-piedzivojumi/makskeresana/makskeresana-ar-naktsmitni",
    "596": "https://www.lieliskadavana.lv/udens-piedzivojumi/brauciens-ar-kugi-vai-jahtu/jahtu-noma",
    "597": "https://www.lieliskadavana.lv/udens-piedzivojumi/brauciens-ar-kugi-vai-jahtu/motorjahtas",
    "598": "https://www.lieliskadavana.lv/udens-piedzivojumi/plosti",
    "599": "https://www.lieliskadavana.lv/udens-piedzivojumi/udens-formulas",
    "600": "https://www.lieliskadavana.lv/udens-piedzivojumi/efoil",
    "612": "https://www.lieliskadavana.lv/kursi-un-meistarklases/meistarklases",
    "613": "https://www.lieliskadavana.lv/kursi-un-meistarklases/meistarklases/berniem-meistarklases",
    "614": "https://www.lieliskadavana.lv/kursi-un-meistarklases/meistarklases/meistarklases-sievietem",
    "615": "https://www.lieliskadavana.lv/kursi-un-meistarklases/meistarklases/meistarklases-viriesiem",
    "617": "https://www.lieliskadavana.lv/kursi-un-meistarklases/kursi/auto-kursi",
    "618": "https://www.lieliskadavana.lv/kursi-un-meistarklases/kursi-pieaugusajiem",
    "619": "https://www.lieliskadavana.lv/kursi-un-meistarklases/keramikas-meistarklase",
    "620": "https://www.lieliskadavana.lv/kursi-un-meistarklases/gatavosanas-meistarklases",
    "621": "https://www.lieliskadavana.lv/kursi-un-meistarklases/gatavosanas-meistarklases/makarunu-meistarklase",
    "622": "https://www.lieliskadavana.lv/kursi-un-meistarklases/gatavosanas-meistarklases/kuku-cepsanas-meistarklase",
    "623": "https://www.lieliskadavana.lv/kursi-un-meistarklases/gatavosanas-meistarklases/picu-meistarklase",
    "624": "https://www.lieliskadavana.lv/kursi-un-meistarklases/zimesanas-kursi",
    "631": "https://www.lieliskadavana.lv/jautras-davanas/preses-abonementi/zurnali-viriesiem",
    "632": "https://www.lieliskadavana.lv/jautras-davanas/preses-abonementi/bernu-zurnali",
    "633": "https://www.lieliskadavana.lv/jautras-davanas/preses-abonementi/jauniesu-zurnali",
    "634": "https://www.lieliskadavana.lv/jautras-davanas/preses-abonementi/krustvardu-miklas",
    "635": "https://www.lieliskadavana.lv/veselibai-un-labsajutai/pirts/pirtis-riga",
    "636": "https://www.lieliskadavana.lv/veselibai-un-labsajutai/pirts/pirtis-pieriga",
    "637": "https://www.lieliskadavana.lv/veselibai-un-labsajutai/pirts/koka-pirtis",
    "638": "https://www.lieliskadavana.lv/veselibai-un-labsajutai/pirts/mazas-pirtis",
    "639": "https://www.lieliskadavana.lv/veselibai-un-labsajutai/pirts/pirts-majas",
    "640": "https://www.lieliskadavana.lv/veselibai-un-labsajutai/pirts/pirtis-ar-kublu",
    "641": "https://www.lieliskadavana.lv/veselibai-un-labsajutai/pirts-rituals/pirts-rituals-diviem",
    "642": "https://www.lieliskadavana.lv/veselibai-un-labsajutai/pirts-rituals/pirts-rituals-ar-pirtnieku",
    "643": "https://www.lieliskadavana.lv/veselibai-un-labsajutai/pirts-rituals/pirts-spa",
    "644": "https://www.lieliskadavana.lv/veselibai-un-labsajutai/baseini/baseini-riga",
    "645": "https://www.lieliskadavana.lv/veselibai-un-labsajutai/baseini/baseini-jurmala",
    "650": "https://www.lieliskadavana.lv/aktiva-atputa/golfs",
    "651": "https://www.lieliskadavana.lv/aktiva-atputa/golfs/klasiskais-golfs",
    "652": "https://www.lieliskadavana.lv/aktiva-atputa/golfs/disku-golfs",
    "653": "https://www.lieliskadavana.lv/aktiva-atputa/golfs/mini-golf",
    "654": "https://www.lieliskadavana.lv/aktiva-atputa/golfs/futbolgolfs",
    "655": "https://www.lieliskadavana.lv/aktiva-atputa/skvoss",
    "656": "https://www.lieliskadavana.lv/aktiva-atputa/izklaides",
    "658": "https://www.lieliskadavana.lv/aktiva-atputa/sporta-klubi",
    "659": "https://www.lieliskadavana.lv/aktiva-atputa/joga",
    "660": "https://www.lieliskadavana.lv/aktiva-atputa/orientesanas",
    "661": "https://www.lieliskadavana.lv/aktiva-atputa/pargajieni",
    "662": "https://www.lieliskadavana.lv/aktiva-atputa/kerlings",
    "663": "https://www.lieliskadavana.lv/aktiva-atputa/kikbokss",
    "665": "https://www.lieliskadavana.lv/davanas-gardeziem/restorani",
    "666": "https://www.lieliskadavana.lv/davanas-gardeziem/restorani/italu-restorans",
    "667": "https://www.lieliskadavana.lv/davanas-gardeziem/restorani/armenu-restorans",
    "668": "https://www.lieliskadavana.lv/davanas-gardeziem/kafejnicas",
    "669": "https://www.lieliskadavana.lv/davanas-gardeziem/kafejnicas/kafejnicas-vecriga",
    "670": "https://www.lieliskadavana.lv/davanas-gardeziem/kafejnicas/kafejnica-rigas-centra",
    "671": "https://www.lieliskadavana.lv/davanas-gardeziem/kafejnicas/omuligas-kafejnicas",
    "672": "https://www.lieliskadavana.lv/davanas-gardeziem/kafejnicas/labakas-kafejnicas-riga",
    "673": "https://www.lieliskadavana.lv/davanas-gardeziem/brokastis",
    "675": "https://www.lieliskadavana.lv/davanas-gardeziem/vakarinas/vakarinas-restorana",
    "676": "https://www.lieliskadavana.lv/davanas-gardeziem/vakarinas/gimenei-draudzigas-vakarinas",
    "677": "https://www.lieliskadavana.lv/davanas-gardeziem/vakarinas/kur-paest-vakarinas-riga",
    "679": "https://www.lieliskadavana.lv/davanas-gardeziem/degustacijas/smakovkas-degustacija",
    "680": "https://www.lieliskadavana.lv/davanas-gardeziem/restorani/picerijas",
    "681": "https://www.lieliskadavana.lv/davanas-gardeziem/restorani/labakie-restorani",
    "682": "https://www.lieliskadavana.lv/aktiva-atputa/padel-teniss",
    "684": "https://www.lieliskadavana.lv/lidojumi-un-lecieni/lidojumi-ar-gaisa-balonu/lidojums-ar-gaisa-balonu-jelgava",
    "685": "https://www.lieliskadavana.lv/lidojumi-un-lecieni/lidojums-virs-rigas",
    "686": "https://www.lieliskadavana.lv/lidojumi-un-lecieni/lidojums-virs-rigas/lidojums-virs-siguldas",
    "687": "https://www.lieliskadavana.lv/lidojumi-un-lecieni/lidojums-ar-motodeltaplanu",
    "709": "https://www.lieliskadavana.lv/visa-pasaule",
    "712": "https://www.lieliskadavana.lv/skaistumkopsana/frizetava",
    "713": "https://www.lieliskadavana.lv/skaistumkopsana/ausu-caurdursana",
    "714": "https://www.lieliskadavana.lv/skaistumkopsana/ausu-caurdursana/ausu-caurdursana-riga",
    "715": "https://www.lieliskadavana.lv/skaistumkopsana/ausu-caurdursana/ausu-caurdursana-berniem",
    "716": "https://www.lieliskadavana.lv/skaistumkopsana/manikirs/japanu-manikirs",
    "717": "https://www.lieliskadavana.lv/skaistumkopsana/manikirs/francu-manikirs",
    "718": "https://www.lieliskadavana.lv/skaistumkopsana/manikirs/klasiskais-manikirs",
    "719": "https://www.lieliskadavana.lv/skaistumkopsana/pedikirs/arstnieciskais-pedikirs",
    "720": "https://www.lieliskadavana.lv/skaistumkopsana/pedikirs/pedikirs-riga",
    "721": "https://www.lieliskadavana.lv/skaistumkopsana/vaksacija/vaksacija-riga",
    "722": "https://www.lieliskadavana.lv/skaistumkopsana/vaksacija/bikini-vaksacija",
    "723": "https://www.lieliskadavana.lv/skaistumkopsana/vaksacija/vaksacija-viriesiem",
    "724": "https://www.lieliskadavana.lv/skaistumkopsana/vaksacija/vaksacija-viriesiem/muguras-vaksacija-viriesiem",
    "725": "https://www.lieliskadavana.lv/skaistumkopsana/vaksacija/sejas-vaksacija",
    "726": "https://www.lieliskadavana.lv/skaistumkopsana/skropstasuzacis/skropstu-pieaudzesana",
    "727": "https://www.lieliskadavana.lv/skaistumkopsana/skropstasuzacis/skropstu-laminesana",
    "728": "https://www.lieliskadavana.lv/skaistumkopsana/skropstasuzacis/uzacu-laminesana",
    "729": "https://www.lieliskadavana.lv/skaistumkopsana/skropstasuzacis/permanentas-uzacis",
    "730": "https://www.lieliskadavana.lv/skaistumkopsana/skropstasuzacis/uzacu-korekcija",
    "731": "https://www.lieliskadavana.lv/skaistumkopsana/skropstasuzacis/uzacu-krasosana",
    "732": "https://www.lieliskadavana.lv/skaistumkopsana/terapijas",
    "733": "https://www.lieliskadavana.lv/skaistumkopsana/terapijas/mezoterapija",
    "734": "https://www.lieliskadavana.lv/skaistumkopsana/terapijas/krioterapija",
    "735": "https://www.lieliskadavana.lv/skaistumkopsana/terapijas/ultraskanas-terapija",
    "736": "https://www.lieliskadavana.lv/skaistumkopsana/terapijas/endosferas-terapija",
    "737": "https://www.lieliskadavana.lv/skaistumkopsana/lazerepilacija",
    "738": "https://www.lieliskadavana.lv/skaistumkopsana/anti-ageing",
    "739": "https://www.lieliskadavana.lv/skaistumkopsana/liftings",
    "740": "https://www.lieliskadavana.lv/skaistumkopsana/dermapen",
    "741": "https://www.lieliskadavana.lv/skaistumkopsana/kavitacija",
    "744": "https://www.lieliskadavana.lv/skaistumkopsana/terapijas/fizioterapija",
    "756": "https://www.lieliskadavana.lv/kursi-un-meistarklases/kursi/masazu-kursi",
    "757": "https://www.lieliskadavana.lv/naksnosana/glempings",
    "759": "https://www.lieliskadavana.lv/atputa-arzemes/naksnosana-lietuva/klaipeda",
    "760": "https://www.lieliskadavana.lv/spa-un-masazas/spa-palanga",
    "765": "https://www.lieliskadavana.lv/spa-un-masazas/spa-druskininki",
    "766": "https://www.lieliskadavana.lv/kursi-un-meistarklases/smarzu-meistarklase",
    "767": "https://www.lieliskadavana.lv/skaistumkopsana/terapijas/aromaterapija",
    "768": "https://www.lieliskadavana.lv/kursi-un-meistarklases/svecu-liesanas-meistarklase",
    "770": "https://www.lieliskadavana.lv/davanas-gardeziem/azijas-virtuve",
    "771": "https://www.lieliskadavana.lv/aktiva-atputa/biljards",
    "780": "https://www.lieliskadavana.lv/veselibai-un-labsajutai/pilates",
    "781": "https://www.lieliskadavana.lv/naksnosana/pils",
    "782": "https://www.lieliskadavana.lv/rotaslietas",
}
