"""Category catalog for PL - Generated from tree file."""

# Category ID to Name mapping
CATEGORY_NAME_MAP: dict[str, str] = {
    "355": "Loty",
    "356": "Lot paralotnią",
    "358": "Lot samolotem",
    "359": "Lot szybowcem",
    "360": "Lot helikopterem",
    "361": "Lot balonem",
    "362": "Kurs pilotażu",
    "363": "Tunel aerodynamiczny",
    "364": "Skok ze spadochronem",
    "365": "Dream Jump",
    "366": "Lot widokowy",
    "367": "Jazda",
    "369": "Off-road",
    "370": "Gokarty",
    "371": "Motocykle",
    "372": "Quady",
    "374": "Pojazdy specjalne",
    "375": "Nauka bezpiecznej jazdy",
    "376": "Sporty wodne",
    "377": "Flyboard",
    "378": "Windsurfing",
    "379": "Skutery wodne",
    "380": "Nurkowanie",
    "381": "Jachty",
    "382": "Spływ kajakowy",
    "383": "Aquapark",
    "384": "Żeglarstwo",
    "385": "Wakeboarding",
    "387": "Zdrowie i relaks",
    "388": "Masaże",
    "389": "Zabiegi na ciało",
    "390": "Zabiegi na twarz",
    "391": "Manicure",
    "392": "SPA i Wellness",
    "393": "Siłownia",
    "394": "Grota solna",
    "395": "Metamorfozy",
    "396": "Restauracje i degustacje",
    "397": "Degustacja wina",
    "398": "Warsztaty kulinarne",
    "399": "Teatr",
    "400": "Strzelanie",
    "401": "Strzelnica",
    "402": "Paintball",
    "403": "Paintball laserowy",
    "405": "Sesja fotograficzna",
    "406": "Kurs fotografii",
    "407": "Kultura i rozrywka",
    "408": "Jazda konna",
    "409": "Wspinaczka",
    "410": "Nauka tańca",
    "411": "Tenis",
    "412": "Survival",
    "413": "Golf",
    "414": "Podróże",
    "415": "Mazury",
    "416": "Góry",
    "417": "Morze",
    "418": "Weekend w mieście",
    "420": "Pobyt w SPA",
    "421": "Nauka i zabawa",
    "423": "Warsztaty kreatywne",
    "424": "Kursy pilotażu",
    "427": "Kursy kompetencyjne",
    "489": "Zestawy podarunkowe",
    "501": "SUPERsamochody",
    "503": "Tor Poznań",
    "504": "Tor Kartingowy Poznań",
    "505": "Tor Jastrząb k. Radomia",
    "506": "Tor Ułęż",
    "507": "Tor Kamień Śląski",
    "508": "Tor Nowe Miasto nad Pilicą",
    "509": "Tor Warszawa Bemowo",
    "510": "Tor Piaseczno k. Warszawy",
    "511": "Tor Pruszcz Gdański",
    "512": "Tor Wrocław Rakietowa",
    "527": "Escape Room",
    "531": "Skoki",
    "532": "Skok na bungee",
    "543": "Drifting",
    "544": "Pojedynki samochodów",
    "547": "Tor Borsk",
    "559": "Samochody rajdowe",
    "560": "Samochody sportowe",
    "568": "Pojazdy militarne",
    "578": "Parki rozrywki",
    "593": "Romantyczna kolacja",
    "594": "Deser",
    "595": "Kawa i Herbata",
    "605": "Wirtualna rzeczywistość",
    "615": "Sporty zimowe",
    "616": "Ekskluzywne prezenty",
    "618": "Jazda po mieście",
    "651": "Rafting",
    "652": "Sporty Ekstremalne",
    "659": "Floating",
    "676": "Pakiety medyczne",
    "678": "Kurs baristy",
    "679": "Kurs na barmana",
    "680": "Bilard",
    "681": "Kręgle",
    "682": "Pobyt w sanatorium",
    "683": "Weekend w SPA",
    "684": "Wycieczki weekendowe",
    "685": "Jazda Lamborghini",
    "686": "Jazda Ferrari",
    "687": "Jazda 4x4",
    "688": "Termy",
    "689": "Kitesurfing",
    "690": "Motorówka",
    "691": "Rejs statkiem",
    "692": "Kurs żeglarski",
    "693": "Kurs motorowodny",
    "694": "Rzucanie siekierami",
    "715": "Makijaż i wizaż",
    "716": "Zabiegi kosmetyczne",
    "717": "Pedicure",
    "718": "Kolacje dla dwojga",
    "719": "Restauracja w ciemności",
    "720": "Degustacja whisky",
    "721": "Degustacja piwa",
    "722": "Kino",
    "723": "Kursy językowe",
    "724": "Warsztaty muzyczne",
    "725": "Uroda",
    "726": "Blisko natury",
    "727": "Zwierzęta",
    "728": "Przyroda",
    "729": "Aktywny wypoczynek",
    "730": "Park trampolin",
    "731": "Park linowy",
    "732": "Fitness",
    "733": "Joga",
    "734": "Squash",
    "735": "Tyrolka",
    "736": "Lot motolotnią",
    "749": "Atrakcje bez wychodzenia z domu",
    "751": "Jedzenie na wynos",
    "752": "Kursy i warsztaty online",
    "781": "Wypoczynek za granicą",
    "782": "Wypoczynek na Litwie",
    "783": "Inne kraje",
    "787": "Masaż tajski",
    "788": "Masaż bańką chińską",
    "789": "Masaż relaksacyjny",
    "790": "Masaż lomi lomi",
    "791": "Masaż klasyczny",
    "792": "Masaż kamieniami",
    "793": "Masaż balijski",
    "794": "Masaż twarzy",
    "795": "Masaż stóp",
    "796": "Masaż pleców",
    "797": "Masaż ajurwedyjski",
    "798": "Masaż leczniczy",
    "799": "Masaż orientalny",
    "800": "Masaż sportowy",
    "801": "Masaż głowy",
    "802": "Masaż dla dwojga",
    "803": "Masaż czekoladą",
    "804": "Masaż w ciąży",
    "805": "Masaż całego ciała",
    "806": "Masaż stemplami",
    "807": "Masaż miodem",
    "808": "Masaż aromaterapeutyczny",
    "809": "Masaż świecą",
    "814": "Jazda po torze",
    "815": "Nauka jazdy samochodem",
    "816": "Szybkie auta",
    "854": "Strzelanie z broni palnej",
    "855": "Strzelanie z karabinu",
    "856": "Strzelanie z pistoletu",
    "857": "Strzelanie z broni historycznej",
    "858": "Nauka strzelania",
    "859": "Strzelanie dynamiczne",
    "860": "Strzelectwo sportowe",
    "861": "Strzelanie dla dzieci",
    "862": "Strzelanie dla dwojga",
    "863": "Strzelanie z łuku",
    "864": "Strzelanie do rzutków",
    "868": "Bony podarunkowe do sklepów",
    "871": "tor Bednary",
    "872": "tor Poznań",
    "873": "tor Poznań Główny",
    "874": "tor Poznań kartingowy",
    "875": "tor Białystok",
    "876": "tor Driveland (Słabomierz)",
    "877": "tor Jastrząb",
    "878": "tor Koszalin",
    "879": "tor Kraków",
    "880": "tor Krzywa (Wrocław)",
    "881": "tor Łódź",
    "882": "tor Pszczółki",
    "883": "tor Słomczyn",
    "884": "tor Toruń",
    "885": "tor Ułęż",
    "886": "tor Silesia Ring",
    "887": "tor Silesia Ring Główny",
    "888": "tor Silesia Ring kartingowy",
    "889": "tor Modlin",
    "890": "tor Olsztyn",
    "891": "tor Kielce",
    "892": "tor Bemowo",
    "894": "Wynajem samochodów",
    "895": "Jazda crossem",
    "896": "Jazda skuterem",
    "897": "Szkolenie motocyklowe",
    "898": "Jazda Fordem",
    "899": "Jazda Audi",
    "900": "Jazda Nissanem",
    "901": "Jazda bolidem",
    "902": "Jazda BMW",
    "903": "Jazda Porsche",
    "904": "Jazda Mitsubishi",
    "905": "Monster Truck",
    "906": "Jazda czołgiem",
    "907": "Jazda Teslą",
    "908": "Jazda Subaru",
    "944": "Glamping",
    "950": "Karty podarunkowe do centrów handlowych",
    "975": "Lot awionetką",
    "976": "Wycieczki jednodniowe",
    "984": "Kursy kulinarne",
    "998": "Miejskie karty podarunkowe",
    "999": "Muzeum",
    "1000": "Sauna",
    "1001": "Masaż Kobido",
    "1003": "Sztuki walki",
    "1004": "Romantyczny weekend dla dwojga z jacuzzi w pokoju",
    "1005": "Tlenoterapia",
    "1014": "Nauka śpiewu",
    "1015": "Stylizacja włosów",
    "1017": "Skok w tandemie",
    "1019": "Nauka rysunku",
    "1021": "Pobyt w SPA z zabiegami",
    "1022": "Tor motocyklowy",
    "1023": "Weekend w SPA nad morzem",
    "1029": "Zakupy ze stylistką",
    "1033": "Gokarty Kraków",
    "1034": "Nauka gry na instrumentach",
    "1037": "Jazda Buggy",
    "1040": "Jazda Harleyem",
    "1042": "Jazda ogórkiem",
    "1043": "Jazda ciężarówką",
    "1044": "Włochy",
    "1045": "Węgry",
    "1046": "Norwegia",
    "1094": "SPA",
    "1095": "Uzdrowisko",
    "1096": "Hammam",
    "1097": "Head SPA",
    "1098": "SPA dla dwojga",
    "1099": "SPA hotel",
    "1100": "SPA resort",
    "1101": "Day SPA",
    "1102": "SPA dla kobiet",
    "1103": "Zabieg SPA",
    "1104": "SPA dla mężczyzn",
    "1105": "Hotel",
    "1106": "Zamek",
    "1107": "Sanatorium",
    "1108": "Nocleg nad morzem",
    "1109": "Dwór",
    "1110": "Domek na drzewie",
    "1111": "Domki w górach",
    "1112": "Weekend dla dwojga",
    "1113": "Willa",
    "1114": "Pensjonat",
    "1115": "Resort",
    "1117": "Wakacje w Polsce",
    "1118": "Restauracje",
    "1119": "Restauracja Polska",
    "1120": "Restauracja Wegetariańska",
    "1121": "Restauracja Włoska",
    "1122": "Restauracja Rybna",
    "1123": "Sushi",
    "1124": "Karczma",
    "1125": "Steakhouse",
    "1126": "Winnica",
    "1128": "Degustacje",
    "1131": "Drenaż Limfatyczny",
    "1132": "Refleksologia",
    "1134": "Masaż Tkanek Głębokich",
    "1135": "Masaż Gorącymi Kamieniami",
    "1136": "Masaż Shiatsu",
    "1137": "Masaż Antycellulitowy",
    "1138": "Masaż Karku",
    "1139": "Masaż Dłoni",
    "1140": "Masaż Dla Kobiet W Ciąży",
    "1141": "Masaż Stemplami Ziołowymi",
    "1142": "Minigolf",
    "1143": "Park rozrywki",
    "1144": "Ścianka wspinaczkowa",
    "1145": "Pole dance",
    "1146": "Okulary VR",
    "1148": "Buggy",
    "1150": "Nauka Jazdy",
    "1151": "Przejażdżka Lamborghini",
    "1152": "Przejażdżka Ferrari",
    "1153": "Jazda po torze wyścigowym",
    "1154": "Przejażdżka Porsche",
    "1155": "Przejażdżka Czołgiem",
    "1156": "Jazda Na Torze Wyścigowym",
    "1157": "Kurs Jazdy Ekstremalnej",
    "1158": "Fun&Creative",
    "1159": "Warsztaty",
    "1160": "Warsztaty dla dzieci",
    "1161": "Ciekawe warsztaty dla dorosłych",
    "1162": "Szkolenie",
    "1163": "Szkolenie psów",
    "1164": "Kursy",
    "1165": "Kurs makijażu",
    "1169": "Sesja zdjęciowa",
    "1170": "Lekcja tańca",
    "1171": "Gra miejska",
    "1172": "Loty i skoki",
    "1173": "Lot Motoparalotnią",
    "1177": "Peelingi",
    "1183": "SUP",
}

# Category ID to URL mapping
CATEGORY_URL_MAP: dict[str, str] = {
    "355": "https://www.superprezenty.pl/loty",
    "356": "https://www.superprezenty.pl/loty/lot-paralotnia",
    "358": "https://www.superprezenty.pl/loty/loty-samolotem",
    "359": "https://www.superprezenty.pl/loty/loty-szybowcem",
    "360": "https://www.superprezenty.pl/loty/loty-helikopterem",
    "361": "https://www.superprezenty.pl/loty/loty-balonem",
    "362": "https://www.superprezenty.pl/loty/kurs-pilotazu",
    "363": "https://www.superprezenty.pl/skoki/tunel-aerodynamiczny",
    "364": "https://www.superprezenty.pl/skoki/skoki-spadochronowe",
    "365": "https://www.superprezenty.pl/skoki/dream-jump",
    "366": "https://www.superprezenty.pl/loty/loty-widokowe",
    "367": "https://www.superprezenty.pl/jazda",
    "369": "https://www.superprezenty.pl/jazda/off-road",
    "370": "https://www.superprezenty.pl/jazda/gokarty",
    "371": "https://www.superprezenty.pl/jazda/motocykle",
    "372": "https://www.superprezenty.pl/jazda/quady",
    "374": "https://www.superprezenty.pl/jazda/pojazdy-specjalne",
    "375": "https://www.superprezenty.pl/jazda/nauka-jazdy/nauka-bezpiecznej-jazdy",
    "376": "https://www.superprezenty.pl/sporty-wodne",
    "377": "https://www.superprezenty.pl/sporty-wodne/flyboard",
    "378": "https://www.superprezenty.pl/sporty-wodne/windsurfing",
    "379": "https://www.superprezenty.pl/sporty-wodne/skutery-wodne",
    "380": "https://www.superprezenty.pl/sporty-wodne/nurkowanie",
    "381": "https://www.superprezenty.pl/sporty-wodne/jachty",
    "382": "https://www.superprezenty.pl/sporty-wodne/kajaki",
    "383": "https://www.superprezenty.pl/sporty-wodne/aquapark",
    "384": "https://www.superprezenty.pl/sporty-wodne/zeglarstwo",
    "385": "https://www.superprezenty.pl/sporty-wodne/wakeboarding",
    "387": "https://www.superprezenty.pl/zdrowie-i-relaks",
    "388": "https://www.superprezenty.pl/masaze",
    "389": "https://www.superprezenty.pl/uroda/zabiegi-na-cialo",
    "390": "https://www.superprezenty.pl/uroda/zabiegi-na-twarz",
    "391": "https://www.superprezenty.pl/uroda/manicure",
    "392": "https://www.superprezenty.pl/zdrowie-i-relaks/spa-i-wellness",
    "393": "https://www.superprezenty.pl/aktywny-wypoczynek/silownia",
    "394": "https://www.superprezenty.pl/zdrowie-i-relaks/grota-solna",
    "395": "https://www.superprezenty.pl/uroda/metamorfozy",
    "396": "https://www.superprezenty.pl/kulinaria",
    "397": "https://www.superprezenty.pl/kulinaria/degustacje/degustacja-wina",
    "398": "https://www.superprezenty.pl/kulinaria/warsztatow-kulinarnych",
    "399": "https://www.superprezenty.pl/kultura-i-rozrywka/teatry",
    "400": "https://www.superprezenty.pl/strzelectwo",
    "401": "https://www.superprezenty.pl/strzelectwo/strzelnica",
    "402": "https://www.superprezenty.pl/strzelectwo/paintball",
    "403": "https://www.superprezenty.pl/strzelectwo/paintball-laserowy",
    "405": "https://www.superprezenty.pl/nauka-i-zabawa/sesja-fotograficzna",
    "406": "https://www.superprezenty.pl/nauka-i-zabawa/kurs-fotografii",
    "407": "https://www.superprezenty.pl/kultura-i-rozrywka",
    "408": "https://www.superprezenty.pl/aktywny-wypoczynek/jazda-konna",
    "409": "https://www.superprezenty.pl/aktywny-wypoczynek/wspinaczka",
    "410": "https://www.superprezenty.pl/nauka-i-zabawa/nauka-tanca",
    "411": "https://www.superprezenty.pl/aktywny-wypoczynek/tenis",
    "412": "https://www.superprezenty.pl/blisko-natury/survival",
    "413": "https://www.superprezenty.pl/aktywny-wypoczynek/golf",
    "414": "https://www.superprezenty.pl/podroze",
    "415": "https://www.superprezenty.pl/podroze/mazury",
    "416": "https://www.superprezenty.pl/podroze/gory",
    "417": "https://www.superprezenty.pl/podroze/morze",
    "418": "https://www.superprezenty.pl/podroze/weekend-w-miescie",
    "420": "https://www.superprezenty.pl/podroze/pobyt-w-spa",
    "421": "https://www.superprezenty.pl/nauka-i-zabawa",
    "423": "https://www.superprezenty.pl/nauka-i-zabawa/warsztaty-artystyczne",
    "424": "https://www.superprezenty.pl/nauka-i-zabawa/kursy-pilotazu",
    "427": "https://www.superprezenty.pl/nauka-i-zabawa/kursy-kompetencyjne",
    "489": "https://www.superprezenty.pl/zestawy-podarunkowe",
    "501": "https://www.superprezenty.pl/jazda/samochody-sportowe/supersamochody",
    "503": "https://www.superprezenty.pl/jazda/samochody-sportowe/supersamochody/tory/tor-poznan",
    "504": "https://www.superprezenty.pl/jazda/samochody-sportowe/supersamochody/tory/tor-kartingowy-poznan",
    "505": "https://www.superprezenty.pl/jazda/samochody-sportowe/supersamochody/tory/tor-jastrzab-k-radomia",
    "506": "https://www.superprezenty.pl/jazda/samochody-sportowe/supersamochody/tory/tor-ulez",
    "507": "https://www.superprezenty.pl/jazda/samochody-sportowe/supersamochody/tory/tor-kamien-slaski",
    "508": "https://www.superprezenty.pl/jazda/samochody-sportowe/supersamochody/tory/tor-nowe-miasto-nad-pilica",
    "509": "https://www.superprezenty.pl/jazda/samochody-sportowe/supersamochody/tory/tor-warszawa-bemowo",
    "510": "https://www.superprezenty.pl/jazda/samochody-sportowe/supersamochody/tory/tor-piaseczno-k-warszawy",
    "511": "https://www.superprezenty.pl/jazda/samochody-sportowe/supersamochody/tory/tor-pruszcz-gdanski",
    "512": "https://www.superprezenty.pl/jazda/samochody-sportowe/supersamochody/tory/tor-wroclaw-rakietowa",
    "527": "https://www.superprezenty.pl/kultura-i-rozrywka/escape-room",
    "531": "https://www.superprezenty.pl/skoki",
    "532": "https://www.superprezenty.pl/skoki/skoki-bungee",
    "543": "https://www.superprezenty.pl/jazda/drifting",
    "544": "https://www.superprezenty.pl/jazda/samochody-sportowe/supersamochody/pojedynki-samochodow",
    "547": "https://www.superprezenty.pl/jazda/samochody-sportowe/supersamochody/tory/tor-borsk",
    "559": "https://www.superprezenty.pl/jazda/samochody-rajdowe",
    "560": "https://www.superprezenty.pl/jazda/samochody-sportowe",
    "568": "https://www.superprezenty.pl/jazda/pojazdy-militarne",
    "578": "https://www.superprezenty.pl/kultura-i-rozrywka/park-rozrywki",
    "593": "https://www.superprezenty.pl/kulinaria/romantyczna-kolacja",
    "594": "https://www.superprezenty.pl/kulinaria/desery-i-slodkosci",
    "595": "https://www.superprezenty.pl/kulinaria/kawa-i-herbata",
    "605": "https://www.superprezenty.pl/kultura-i-rozrywka/wirtualna-rzeczywistosc",
    "615": "https://www.superprezenty.pl/aktywny-wypoczynek/sporty-zimowe",
    "616": "https://www.superprezenty.pl/ekskluzywne-prezenty",
    "618": "https://www.superprezenty.pl/jazda/samochody-sportowe/supersamochody/jazda-po-miescie",
    "651": "https://www.superprezenty.pl/sporty-wodne/rafting",
    "652": "https://www.superprezenty.pl/sporty-ekstremalne",
    "659": "https://www.superprezenty.pl/spa/floating",
    "676": "https://www.superprezenty.pl/zdrowie-i-relaks/uslugi-medyczne",
    "678": "https://www.superprezenty.pl/kulinaria/kurs-baristy",
    "679": "https://www.superprezenty.pl/kulinaria/kurs-na-barmana",
    "680": "https://www.superprezenty.pl/kultura-i-rozrywka/bilard",
    "681": "https://www.superprezenty.pl/kultura-i-rozrywka/kregle",
    "682": "https://www.superprezenty.pl/podroze/pobyt-w-sanatorium",
    "683": "https://www.superprezenty.pl/podroze/weekend-w-spa",
    "684": "https://www.superprezenty.pl/podroze/wycieczki-weekendowe",
    "685": "https://www.superprezenty.pl/jazda/samochody-sportowe/supersamochody/jazda-lamborghini",
    "686": "https://www.superprezenty.pl/jazda/samochody-sportowe/supersamochody/jazda-ferrari",
    "687": "https://www.superprezenty.pl/jazda/samochody-sportowe/supersamochody/jazda-4x4",
    "688": "https://www.superprezenty.pl/spa/termy",
    "689": "https://www.superprezenty.pl/sporty-wodne/kitesurfing",
    "690": "https://www.superprezenty.pl/sporty-wodne/motorowki",
    "691": "https://www.superprezenty.pl/sporty-wodne/rejs-statkiem",
    "692": "https://www.superprezenty.pl/sporty-wodne/kursy-zeglarskie",
    "693": "https://www.superprezenty.pl/sporty-wodne/kurs-motorowodny",
    "694": "https://www.superprezenty.pl/strzelectwo/rzucanie-siekierami",
    "715": "https://www.superprezenty.pl/uroda/makijaz-i-wizaz",
    "716": "https://www.superprezenty.pl/uroda/zabiegi-kosmetyczne",
    "717": "https://www.superprezenty.pl/uroda/pedicure",
    "718": "https://www.superprezenty.pl/kulinaria/kolacja-dla-dwojga",
    "719": "https://www.superprezenty.pl/kulinaria/restauracja-w-ciemnosci",
    "720": "https://www.superprezenty.pl/kulinaria/degustacje/degustacja-whisky",
    "721": "https://www.superprezenty.pl/kulinaria/degustacje/degustacja-piwa",
    "722": "https://www.superprezenty.pl/kultura-i-rozrywka/kino",
    "723": "https://www.superprezenty.pl/nauka-i-zabawa/kursy-jezykowe",
    "724": "https://www.superprezenty.pl/kultura-i-rozrywka/warsztaty-muzyczne",
    "725": "https://www.superprezenty.pl/uroda",
    "726": "https://www.superprezenty.pl/blisko-natury",
    "727": "https://www.superprezenty.pl/blisko-natury/zwierzeta",
    "728": "https://www.superprezenty.pl/blisko-natury/przyroda",
    "729": "https://www.superprezenty.pl/aktywny-wypoczynek",
    "730": "https://www.superprezenty.pl/aktywny-wypoczynek/park-trampolin",
    "731": "https://www.superprezenty.pl/aktywny-wypoczynek/park-linowy",
    "732": "https://www.superprezenty.pl/aktywny-wypoczynek/fitness",
    "733": "https://www.superprezenty.pl/aktywny-wypoczynek/joga",
    "734": "https://www.superprezenty.pl/aktywny-wypoczynek/squash",
    "735": "https://www.superprezenty.pl/aktywny-wypoczynek/tyrolka",
    "736": "https://www.superprezenty.pl/loty/lot-motolotnia",
    "749": "https://www.superprezenty.pl/atrakcje-bez-wychodzenia-z-domu",
    "751": "https://www.superprezenty.pl/atrakcje-bez-wychodzenia-z-domu/jedzenie-na-wynos",
    "752": "https://www.superprezenty.pl/atrakcje-bez-wychodzenia-z-domu/kursy-i-warsztaty-online",
    "781": "https://www.superprezenty.pl/podroze/wypoczynek-za-granica",
    "782": "https://www.superprezenty.pl/podroze/wypoczynek-za-granica/wypoczynek-na-litwie",
    "783": "https://www.superprezenty.pl/podroze/wypoczynek-za-granica/inne-kraje",
    "787": "https://www.superprezenty.pl/masaze/masaz-tajski",
    "788": "https://www.superprezenty.pl/masaze/masaz-banka-chinska",
    "789": "https://www.superprezenty.pl/masaze/masaz-relaksacyjny",
    "790": "https://www.superprezenty.pl/masaze/masaz-lomi-lomi",
    "791": "https://www.superprezenty.pl/masaze/masaz-klasyczny",
    "792": "https://www.superprezenty.pl/masaze/masaz-kamieniami",
    "793": "https://www.superprezenty.pl/masaze/masaz-balijski",
    "794": "https://www.superprezenty.pl/masaze/masaz-twarzy",
    "795": "https://www.superprezenty.pl/masaze/masaz-stop",
    "796": "https://www.superprezenty.pl/masaze/masaz-plecow",
    "797": "https://www.superprezenty.pl/masaze/masaz-ajurwedyjski",
    "798": "https://www.superprezenty.pl/masaze/masaz-leczniczy",
    "799": "https://www.superprezenty.pl/masaze/masaz-orientalny",
    "800": "https://www.superprezenty.pl/masaze/masaz-sportowy",
    "801": "https://www.superprezenty.pl/masaze/masaz-glowy",
    "802": "https://www.superprezenty.pl/masaze/masaz-dla-dwojga",
    "803": "https://www.superprezenty.pl/masaze/masaz-czekolada",
    "804": "https://www.superprezenty.pl/masaze/masaz-w-ciazy",
    "805": "https://www.superprezenty.pl/masaze/masaz-calego-ciala",
    "806": "https://www.superprezenty.pl/masaze/masaz-stemplami",
    "807": "https://www.superprezenty.pl/masaze/masaz-miodem",
    "808": "https://www.superprezenty.pl/masaze/masaz-aromaterapeutyczny",
    "809": "https://www.superprezenty.pl/masaze/masaz-swieca",
    "814": "https://www.superprezenty.pl/jazda/jazda-po-torze",
    "815": "https://www.superprezenty.pl/jazda/nauka-jazdy/nauka-jazdy",
    "816": "https://www.superprezenty.pl/jazda/szybkie-auta",
    "854": "https://www.superprezenty.pl/strzelectwo/strzelnica/strzelanie-z-broni-palnej",
    "855": "https://www.superprezenty.pl/strzelectwo/strzelnica/strzelanie-z-broni-palnej/strzelanie-z-karabinu",
    "856": "https://www.superprezenty.pl/strzelectwo/strzelnica/strzelanie-z-broni-palnej/strzelanie-z-pistoletu",
    "857": "https://www.superprezenty.pl/strzelectwo/strzelnica/strzelanie-z-broni-palnej/strzelanie-z-broni-historycznej",
    "858": "https://www.superprezenty.pl/strzelectwo/strzelnica/nauka-strzelania",
    "859": "https://www.superprezenty.pl/strzelectwo/strzelnica/strzelanie-dynamiczne",
    "860": "https://www.superprezenty.pl/strzelectwo/strzelnica/strzelectwo-sportowe",
    "861": "https://www.superprezenty.pl/strzelectwo/strzelanie-dla-dzieci",
    "862": "https://www.superprezenty.pl/strzelectwo/strzelanie-dla-dwojga",
    "863": "https://www.superprezenty.pl/strzelectwo/strzelanie-z-luku",
    "864": "https://www.superprezenty.pl/strzelectwo/strzelnica/strzelanie-do-rzutkow",
    "868": "https://www.superprezenty.pl/bony-podarunkowe-do-sklepow",
    "871": "https://www.superprezenty.pl/jazda/jazda-po-torze/tor-bednary",
    "872": "https://www.superprezenty.pl/jazda/jazda-po-torze/tor-poznan",
    "873": "https://www.superprezenty.pl/jazda/jazda-po-torze/tor-poznan/tor-poznan-glowny",
    "874": "https://www.superprezenty.pl/jazda/jazda-po-torze/tor-poznan/tor-poznan-kartingowy",
    "875": "https://www.superprezenty.pl/jazda/jazda-po-torze/tor-bialystok",
    "876": "https://www.superprezenty.pl/jazda/jazda-po-torze/tor-driveland",
    "877": "https://www.superprezenty.pl/jazda/jazda-po-torze/tor-jastrzab",
    "878": "https://www.superprezenty.pl/jazda/jazda-po-torze/tor-koszalin",
    "879": "https://www.superprezenty.pl/jazda/jazda-po-torze/tor-krakow",
    "880": "https://www.superprezenty.pl/jazda/jazda-po-torze/tor-krzywa",
    "881": "https://www.superprezenty.pl/jazda/jazda-po-torze/tor-lodz",
    "882": "https://www.superprezenty.pl/jazda/jazda-po-torze/tor-pszczolki",
    "883": "https://www.superprezenty.pl/jazda/jazda-po-torze/tor-slomczyn",
    "884": "https://www.superprezenty.pl/jazda/jazda-po-torze/tor-torun",
    "885": "https://www.superprezenty.pl/jazda/jazda-po-torze/tor-ulez",
    "886": "https://www.superprezenty.pl/jazda/jazda-po-torze/tor-silesia-ring",
    "887": "https://www.superprezenty.pl/jazda/jazda-po-torze/tor-silesia-ring/tor-silesia-ring-glowny",
    "888": "https://www.superprezenty.pl/jazda/jazda-po-torze/tor-silesia-ring/tor-silesia-ring-kartingowy",
    "889": "https://www.superprezenty.pl/jazda/jazda-po-torze/tor-modlin",
    "890": "https://www.superprezenty.pl/jazda/jazda-po-torze/tor-olsztyn",
    "891": "https://www.superprezenty.pl/jazda/jazda-po-torze/tor-kielce",
    "892": "https://www.superprezenty.pl/jazda/jazda-po-torze/tor-bemowo",
    "894": "https://www.superprezenty.pl/jazda/samochody-sportowe/supersamochody/wynajem-samochodow",
    "895": "https://www.superprezenty.pl/jazda/motocykle/jazda-crossem",
    "896": "https://www.superprezenty.pl/jazda/motocykle/jazda-skuterem",
    "897": "https://www.superprezenty.pl/jazda/motocykle/szkolenie-motocyklowe",
    "898": "https://www.superprezenty.pl/jazda/samochody-sportowe/jazda-fordem",
    "899": "https://www.superprezenty.pl/jazda/samochody-sportowe/jazda-audi",
    "900": "https://www.superprezenty.pl/jazda/samochody-sportowe/jazda-nissanem",
    "901": "https://www.superprezenty.pl/jazda/samochody-sportowe/supersamochody/jazda-bolidem",
    "902": "https://www.superprezenty.pl/jazda/samochody-sportowe/jazda-bmw",
    "903": "https://www.superprezenty.pl/jazda/samochody-sportowe/jazda-porsche",
    "904": "https://www.superprezenty.pl/jazda/samochody-rajdowe/jazda-mitsubishi",
    "905": "https://www.superprezenty.pl/jazda/monster-truck",
    "906": "https://www.superprezenty.pl/jazda/jazda-czolgiem",
    "907": "https://www.superprezenty.pl/jazda/samochody-sportowe/jazda-tesla",
    "908": "https://www.superprezenty.pl/jazda/samochody-rajdowe/subaru-jazda",
    "944": "https://www.superprezenty.pl/podroze/glamping",
    "950": "https://www.superprezenty.pl/karty-podarunkowe-centrow-handlowych",
    "975": "https://www.superprezenty.pl/loty/lot-awionetka",
    "976": "https://www.superprezenty.pl/podroze/wycieczki-jednodniowe",
    "984": "https://www.superprezenty.pl/kursy-kulinarne",
    "998": "https://www.superprezenty.pl/miejskie-karty-podarunkowe",
    "999": "https://www.superprezenty.pl/kultura-i-rozrywka/muzeum",
    "1000": "https://www.superprezenty.pl/spa/sauna",
    "1001": "https://www.superprezenty.pl/masaze/masaz-kobido",
    "1003": "https://www.superprezenty.pl/aktywny-wypoczynek/sztuki-walki",
    "1004": "https://www.superprezenty.pl/podroze/romantyczny-weekend-dla-dwojga-z-jacuzzi-w-pokoju",
    "1005": "https://www.superprezenty.pl/zdrowie-i-relaks/tlenoterapia",
    "1014": "https://www.superprezenty.pl/nauka-i-zabawa/nauka-spiewu",
    "1015": "https://www.superprezenty.pl/stylizacja-wlosow",
    "1017": "https://www.superprezenty.pl/skoki/skok-w-tandemie",
    "1019": "https://www.superprezenty.pl/nauka-i-zabawa/nauka-rysunku",
    "1021": "https://www.superprezenty.pl/podroze/pobyt-w-spa-z-zabiegami",
    "1022": "https://www.superprezenty.pl/jazda/tor-motocyklowy",
    "1023": "https://www.superprezenty.pl/podroze/weekend-w-spa-nad-morzem",
    "1029": "https://www.superprezenty.pl/kultura-i-rozrywka/zakupy-ze-stylistka",
    "1033": "https://www.superprezenty.pl/gokarty-krakow",
    "1034": "https://www.superprezenty.pl/nauka-i-zabawa/nauka-gry-na-instrumentach",
    "1037": "https://www.superprezenty.pl/jazda/quady/jazda-buggy",
    "1040": "https://www.superprezenty.pl/jazda/motocykle/jazda-harleyem",
    "1042": "https://www.superprezenty.pl/jazda/pojazdy-specjalne/jazda-ogorkiem",
    "1043": "https://www.superprezenty.pl/jazda/pojazdy-specjalne/jazda-ciezarowka",
    "1044": "https://www.superprezenty.pl/podroze/wypoczynek-za-granica/wlochy",
    "1045": "https://www.superprezenty.pl/podroze/wypoczynek-za-granica/wegry",
    "1046": "https://www.superprezenty.pl/podroze/wypoczynek-za-granica/norwegia",
    "1094": "https://www.superprezenty.pl/spa",
    "1095": "https://www.superprezenty.pl/spa/uzdrowisko",
    "1096": "https://www.superprezenty.pl/spa/hammam",
    "1097": "https://www.superprezenty.pl/spa/head-spa",
    "1098": "https://www.superprezenty.pl/spa/spa-dla-dwojga",
    "1099": "https://www.superprezenty.pl/spa/spa-hotel",
    "1100": "https://www.superprezenty.pl/spa/spa-hotel/spa-resort",
    "1101": "https://www.superprezenty.pl/spa/day-spa",
    "1102": "https://www.superprezenty.pl/spa/spa-dla-kobiet",
    "1103": "https://www.superprezenty.pl/spa/zabieg-spa",
    "1104": "https://www.superprezenty.pl/spa/spa-dla-mezczyzn",
    "1105": "https://www.superprezenty.pl/podroze/hotel",
    "1106": "https://www.superprezenty.pl/podroze/zamek",
    "1107": "https://www.superprezenty.pl/podroze/sanatorium",
    "1108": "https://www.superprezenty.pl/podroze/nocleg-nad-morzem",
    "1109": "https://www.superprezenty.pl/podroze/dwor",
    "1110": "https://www.superprezenty.pl/podroze/domek-na-drzewie",
    "1111": "https://www.superprezenty.pl/podroze/domki-w-gorach",
    "1112": "https://www.superprezenty.pl/podroze/weekend-dla-dwojga",
    "1113": "https://www.superprezenty.pl/podroze/willa",
    "1114": "https://www.superprezenty.pl/podroze/pensjonat",
    "1115": "https://www.superprezenty.pl/podroze/resort",
    "1117": "https://www.superprezenty.pl/podroze/wakacje-w-polsce",
    "1118": "https://www.superprezenty.pl/kulinaria/restauracje",
    "1119": "https://www.superprezenty.pl/kulinaria/restauracje/restauracja-polska",
    "1120": "https://www.superprezenty.pl/kulinaria/restauracje/restauracja-wegetarianska",
    "1121": "https://www.superprezenty.pl/kulinaria/restauracje/restauracja-wloska",
    "1122": "https://www.superprezenty.pl/kulinaria/restauracje/restauracja-rybna",
    "1123": "https://www.superprezenty.pl/kulinaria/sushi",
    "1124": "https://www.superprezenty.pl/kulinaria/karczma",
    "1125": "https://www.superprezenty.pl/kulinaria/steakhouse",
    "1126": "https://www.superprezenty.pl/kulinaria/winnica",
    "1128": "https://www.superprezenty.pl/kulinaria/degustacje",
    "1131": "https://www.superprezenty.pl/masaze/drenaz-limfatyczny",
    "1132": "https://www.superprezenty.pl/masaze/refleksologia",
    "1134": "https://www.superprezenty.pl/masaze/masaz-tkanek-glebokich",
    "1135": "https://www.superprezenty.pl/masaze/masaz-goracymi-kamieniami",
    "1136": "https://www.superprezenty.pl/masaze/masaz-shiatsu",
    "1137": "https://www.superprezenty.pl/masaze/masaz-antycellulitowy",
    "1138": "https://www.superprezenty.pl/masaze/masaz-karku",
    "1139": "https://www.superprezenty.pl/masaze/masaz-dloni",
    "1140": "https://www.superprezenty.pl/masaze/masaz-dla-kobiet-w-ciazy",
    "1141": "https://www.superprezenty.pl/masaze/masaz-stemplami-ziolowymi",
    "1142": "https://www.superprezenty.pl/aktywny-wypoczynek/golf/minigolf",
    "1143": "https://www.superprezenty.pl/aktywny-wypoczynek/park-rozrywki",
    "1144": "https://www.superprezenty.pl/aktywny-wypoczynek/scianka-wspinaczkowa",
    "1145": "https://www.superprezenty.pl/aktywny-wypoczynek/pole-dance",
    "1146": "https://www.superprezenty.pl/aktywny-wypoczynek/okulary-vr",
    "1148": "https://www.superprezenty.pl/jazda/buggy",
    "1150": "https://www.superprezenty.pl/jazda/nauka-jazdy",
    "1151": "https://www.superprezenty.pl/jazda/samochody-sportowe/przejazdzka-lamborghini",
    "1152": "https://www.superprezenty.pl/jazda/samochody-sportowe/przejazdzka-ferrari",
    "1153": "https://www.superprezenty.pl/jazda/samochody-sportowe/supersamochody/jazda-po-torze-wyscigowym",
    "1154": "https://www.superprezenty.pl/jazda/przejazdzka-porsche",
    "1155": "https://www.superprezenty.pl/jazda/przejazdzka-czolgiem",
    "1156": "https://www.superprezenty.pl/jazda/jazda-na-torze-wyscigowym",
    "1157": "https://www.superprezenty.pl/jazda/nauka-jazdy/kurs-jazdy-ekstremalnej",
    "1158": "https://www.superprezenty.pl/funcreative",
    "1159": "https://www.superprezenty.pl/warsztaty",
    "1160": "https://www.superprezenty.pl/warsztaty/warsztaty-dla-dzieci",
    "1161": "https://www.superprezenty.pl/warsztaty/ciekawe-warsztaty-dla-doroslych",
    "1162": "https://www.superprezenty.pl/szkolenie",
    "1163": "https://www.superprezenty.pl/szkolenie/szkolenie-psow",
    "1164": "https://www.superprezenty.pl/kursy",
    "1165": "https://www.superprezenty.pl/kursy/kurs-makijazu",
    "1169": "https://www.superprezenty.pl/sesja-zdjeciowa",
    "1170": "https://www.superprezenty.pl/lekcja-tanca",
    "1171": "https://www.superprezenty.pl/gra-miejska",
    "1172": "https://www.superprezenty.pl/loty-i-skoki",
    "1173": "https://www.superprezenty.pl/lot-motoparalotnia",
    "1177": "https://www.superprezenty.pl/uroda/peelingi",
    "1183": "https://www.superprezenty.pl/sporty-wodne/sup",
}
